### ISSUE TITLE
Can I change the default options?

### ISSUE THREAD

**Issue by MinionsDave** [kekeh/ngx-mydatepicker#10]
Can I change the default options such as dateFormat, dayLabels, monthLabels so that I dont need to  set options every directive

**Comment by kekeh** [comment]
I don't understand what you mean.

**Comment by MinionsDave** [comment]
ok, sorry for my English. I just want to know can I do some global configuration like app.config in angular1

**Comment by kekeh** [comment]
Multiple date pickers can use same options. You can use global options.
