### ISSUE TITLE
datepicker inserted in wrong location.

### ISSUE THREAD

**Issue by dc-m** [kekeh/ngx-mydatepicker#100]
datepicker inserted at the bottom of body instead of where i call the ngx-datepicker meaning that if i use within a modal it is outside my modal context and therefore not on top

To make it appear on top i have to set ngxmdp to have a position:fixed and z-index

**Comment by kekeh** [comment]
Hi @dc-m 

I added new option **appendSelectorToBody** which default value is **false**. So by default the selector (calendar) is now appended under the input field. If you want append it into body set option **appendSelectorToBody** to **true**.

This change is in version **2.1.5**.
