### ISSUE TITLE
Can we initialize the date picker with a JS Date object? This is kind of a feature request

### ISSUE THREAD

**Issue by karthikv-26** [kekeh/ngx-mydatepicker#101]
Currently we can pass a initial value as below.
// Initialized to specific date (09.10.2018)
    model: any = { date: { year: 2018, month: 10, day: 9 } };
It would be developer friendly if we can actually pass a value like below.(Just a suggestion)
  model: any = new Date();

The suggested way will greatly help while using reactive forms when server returns us a valid date which could be seamlessly integrated with the date picker to set the value.

**Comment by kekeh** [comment]
You can already initialize with JS date object. 
```javascript
model: any = { date: { year: 2017, month: 10, day: 21 } };
// or
model: any = { jsdate: new Date() };
```
