### ISSUE TITLE
ISO date support?

### ISSUE THREAD

**Issue by smnbbrv** [kekeh/ngx-mydatepicker#104]
hi,

is ISO date supported? Is there any way to force the CustomValueAccessor to return the ISO (or other supported format) date always?

**Comment by kekeh** [comment]
There is this kind of date model: https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/interfaces/my-date-model.interface.ts

You can implement **dateChanged** callback and try to do conversion: https://github.com/kekeh/ngx-mydatepicker#datechanged-callback

**Comment by smnbbrv** [comment]
Thanks for the hint!
