### ISSUE TITLE
No automatic validation when options changed

### ISSUE THREAD

**Issue by Martin-Wegner** [kekeh/ngx-mydatepicker#107]
When I change the options, like mentioned here https://github.com/kekeh/ngx-mydatepicker/issues/99, the validation is not triggered automatically. And there is no method to trigger the validation programmatically. The only workaround I can see is to call the `writeValue` method.

**Comment by kekeh** [comment]
Can you check this example: https://kekeh.github.io/ngx-mydatepicker

it changes options like in issue #99 when you click any of the check box and after that validation works ok.

Or was that the case?

**Comment by Martin-Wegner** [comment]
@kekeh my new options have other min and max values therefore the current selected date would be invalid but the state keeps VALID until you click into the input field and press a key.

**Comment by Martin-Wegner** [comment]
@kekeh any chance that you will investigate into this issue/feature request?

**Comment by kekeh** [comment]
Hi @Martin-Wegner 

I added new function **isDateValid()**. More info from here: https://github.com/kekeh/ngx-mydatepicker#isdatevalid-function

This change is in version: 2.3.1.

**Comment by Martin-Wegner** [comment]
@kekeh thank you, but this does not work (returns always `false` at startup) :(

```
...
  @ViewChildren(NgxMyDatePickerDirective)
  allDatePickers: QueryList<NgxMyDatePickerDirective>;
...
  ngOnInit(): void {
...
    getMyData().subscribe((myData: MyData) => {
      updateDatePickerModels();
      updateDatePickerOptions();

      this.allDatePickers.changes.subscribe(() => {
        this.allDatePickers.forEach((datePicker: NgxMyDatePickerDirective) => {
          console.log(datePicker.isDateValid()); // will always print false
        });
      });

      setTimeout(() => {
        this.allDatePickers.forEach((datePicker: NgxMyDatePickerDirective) => {
          console.log(datePicker.isDateValid()); // prints the truth
        });
      }, 5000);
...
  }
...
```

And unfortunately this method is not exactly what I wanted :( I meant a validation method which triggers the validation mechanism (like after pressing a key) with the same callback function as `inputFieldChanged`.

**Comment by kekeh** [comment]
try to set isDateValid() call inside setTimeout function. Value of the timeout can be zero. The inputFieldChanged would be one option but There is not change in the input field If you change options. That is why I did it this way.

**Comment by kekeh** [comment]
I changed implementation. Now the **isDateValid** also calls the **inputFieldChanged** callback. README: https://github.com/kekeh/ngx-mydatepicker#isdatevalid-function

Can you try version 2.3.2

**Comment by Martin-Wegner** [comment]
@kekeh cool, this works :) But using `setTimeout()` is odd :(
