### ISSUE TITLE
There is no directive with "exportAs" 

### ISSUE THREAD

**Issue by nerijusgood** [kekeh/ngx-mydatepicker#108]
There is no directive with "exportAs" set to "ngx-mydatepicker" ("" ngx-mydatepicker="" name="reactiveFormsDate" formControlName="date" [options]="datepickerOptions" [ERROR ->]#dp="ngx-mydatepicker" autocomplete="off"/>...

I have imported into modules and also imported options to component. Not sure what is the issue here.

**Comment by kekeh** [comment]
There is **exportAs**: https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/ngx-my-date-picker.input.ts

Did you follow instruction from here: https://github.com/kekeh/ngx-mydatepicker#installation

You can define input box this way:
```html
<input ngx-mydatepicker name="myDate" formControlName="myDate" [options]="myOptions" 
    #dp="ngx-mydatepicker"/>
```

**Comment by marchrius** [comment]
I'm having this error with ngModel version. Added the module into app.module, copy / paste the code in installation section but it says that I don't have an exportAs directive for ngx-mydatepicker

**Comment by marchrius** [comment]
I'm having this error with ngModel version. Added the module into app.module, copy / paste the code in installation section but it says that I don't have an exportAs directive for ngx-mydatepicker
