### ISSUE TITLE
calendar always show  in the left

### ISSUE THREAD

**Issue by Jetxiaoli** [kekeh/ngx-mydatepicker#109]
calendar does not go along with input element
it always show with left:0px;

**Comment by kekeh** [comment]
Here the input and the calendar are positioned ok: https://kekeh.github.io/ngx-mydatepicker/

Or was that the issue?

**Comment by Jetxiaoli** [comment]
It's ok now, I tried to put 2 elements in 1 div, when I separate them into 2 divs, it is ok.
