### ISSUE TITLE
Custom date validation for 2 dates in reactive form

### ISSUE THREAD

**Issue by avvishnu** [kekeh/ngx-mydatepicker#110]
Hi,

I have 2 date fields startDate and endDate. I need to validate start date should be less than end date. I am using reactive form. How can we add a custom validation for 2 fields.

create myForm() {
    this.myForm = new FormGroup({
      startDate: new FormControl('', [Validators.required]),
      endDate: new FormControl('', [Validators.required, this.customValidator]),
    });
}

customValidator(control) {
    // check if startDate is less than endDate control
    return {required: control.value < this.myForm.controls['endDate'].value};
  }

This is throwing an error that ERROR TypeError: Cannot read property 'myForm' of undefined.

It will be great if anyone gimme a clue to solve this.

**Comment by kekeh** [comment]
You can prevent user to select invalid date by disable dates. here is example on how to use disableUntil option: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

here is complete example: https://plnkr.co/edit/f383ob?p=preview both start date and end date picker are disabled based on user selection.

Those example are from mydatepicker but they also work with ngx-mydatepicker component. Plunker demo data pickers are in inline mode. ngx-mydatepicker does not support inline mode but options works.

**Comment by avvishnu** [comment]
Thanks Kekeh !!

**Comment by vinayistar** [comment]
If Im having multiple datepicker. How i will initialize that??
Im using a tab in a wizard. In which there will be multiple cards having datepicker for each. 

ERROR Error: formGroup expects a FormGroup instance. Please pass one in.

& ERROR TypeError: Cannot read property 'get' of undefined.

Since these all datepicker are in 2nd tab and not initialized.
