### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by Anirudh-Konduri** [kekeh/ngx-mydatepicker#112]
[x] Feature Request

Does any one tried this out with Angular version 5 ? Any issues so far ? Any plans to update the package to support Angular v5 ?

**Comment by kekeh** [comment]
Hi @Anirudh-Konduri 

It works with Angular 5. This is example of Angular 5 project: https://github.com/kekeh/ngx-mydatepicker/tree/gh-pages

The project is running here: https://kekeh.github.io/ngx-mydatepicker/
