### ISSUE TITLE
update ingxDpOptions, but fail to update view

### ISSUE THREAD

**Issue by lvfe** [kekeh/ngx-mydatepicker#115]
Hi,
I want to set disabledDates when changing a month. so in onCalendarviewChanged event, i updated mydaterOptions.disabledDates. HOwever, the view just fail to update.
calendarViewChanged($event: IMyCalendarViewChanged) {
    const month = $event.month;
    const year = $event.year;
    const disabledDates = this.getNonWorkingday(month, year);
    let copy: INgxMyDpOptions = JSON.parse(JSON.stringify(this.myDatePickerOptions));
    copy.disableDates = disabledDates;
    this.myDatePickerOptions = copy;
    this.ref.tick();
  }

**Comment by kekeh** [comment]
Here you can find examples on how to dynamically set options: https://github.com/kekeh/mydatepicker/wiki

example are from the mydatepicker but they work also with the ngx-mydatepicker.
