### ISSUE TITLE
Write value throws error

### ISSUE THREAD

**Issue by Ludevik** [kekeh/ngx-mydatepicker#116]
We have a use case where we use `dateOptions.disableUntil` and `dateOptions.disableSince`. These two properties change based on checkbox form control. So when user changes the value of the checkbox, disableUntil  & disableSince change. We change these two properties in `valueChanges` checkbox form control callback. Problem is when we call `formGroup.reset()`. It throws error as the value that we want to set is currently not valid, because the date that we want to set is disabled. But it will be valid as soon as the other formControl is changed and its valueChanges callback will be called (changing disabledUntil & disableSince).

Question is whether [write value](https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/ngx-my-date-picker.input.ts#L139) should throw error or just ignore that the value that we want to set is not valid and just add validation error to the control.

**Comment by cvoro** [comment]
I have the same issue when I want to set inputs from backend I get "The value you want to set is invalid"

Did you find what is causing this error? I have to mention that it's working fine with angular 4+ but with angular 5+ I get this error

**Comment by kekeh** [comment]
I did a fix. Now error is not thrown if the date that is set is invalid (for example disabled date). Now component set the date and calls **inputFieldChanged** callback with **valid** flag of **false**.

This change is in version 2.4.0. Please update to this version.
