### ISSUE TITLE
Error: Uncaught (in promise): Error: The value you want to set is invalid

### ISSUE THREAD

**Issue by cvoro** [kekeh/ngx-mydatepicker#117]
I have an issue updating project to angular 5+ I cant set inputs

"dependencies": {
        "@angular/animations": "^5.1.2",
        "@angular/cdk": "^5.0.2",
        "@angular/common": "^5.1.2",
        "@angular/compiler": "^5.1.2",
        "@angular/core": "^5.1.2",
        "@angular/forms": "^5.1.2",
        "@angular/http": "^5.1.2",
        "@angular/material": "^5.0.2",
        "@angular/platform-browser": "^5.1.2",
        "@angular/platform-browser-dynamic": "^5.1.2",
        "@angular/router": "^5.1.2",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
        "@ngx-translate/core": "^8.0.0",
        "@ngx-translate/http-loader": "^2.0.0",
        "angular2-material-datepicker": "^0.5.0",
        "bootstrap": "^4.0.0-alpha.6",
        "core-js": "^2.5.1",
        "font-awesome": "^4.7.0",
        "jquery": "^3.0.0",
        "md5": "^2.2.1",
        "ng2-img-cropper": "^0.9.0",
        "ng2-toastr": "^4.1.2",
        "ng4-loader-bar": "^1.0.3",
        "ngx-mydatepicker": "^2.1.5",
        "ngx-order-pipe": "^1.0.4",
        "ngx-toastr": "^6.4.0",
        "popper.js": "^1.11.0",
        "rxjs": "^5.5.6",
        "tinymce": "^4.7.1",
        "zone.js": "^0.8.18"
    },
    "devDependencies": {
        "@angular/cli": "^1.4.7",
        "@angular/compiler-cli": "^5.1.2",
        "@angular/platform-server": "^5.1.2",
        "@types/jasmine": "2.6.0",
        "@types/node": "^8.0.34",
        "codelyzer": "^3.2.1",
        "jasmine-core": "~2.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.3.0",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "node-sass": "4.5.3",
        "protractor": "~5.1.0",
        "ts-node": "~3.3.0",
        "tslint": "~5.7.0",
        "typescript": "^2.4.2"
    }

@kekeh

**Comment by kekeh** [comment]
I fixed this issue. For more information see #116.

New version of the component is 2.4.0.

**Comment by cvoro** [comment]
Yes, but after focusing field it will be invalid I have found a solution to install ~2.1.5 which is working fine even with angular 5+
