### ISSUE TITLE
Datepicker closes after year or month changes

### ISSUE THREAD

**Issue by VladislavBI** [kekeh/ngx-mydatepicker#118]
I have used 2.1.3 version before and I have no problems neither with year nor with month change on datapicker . After I have updated my package and have installed 2.4.0 version this appends. Please contact me if you will need any additional details

**Comment by kekeh** [comment]
Hi @VladislavBI 

Can you provide step by step instructions on how to reproduce this issue.

**Comment by kekeh** [comment]
Closing because no answer.
