### ISSUE TITLE
My-Date-Picker Styling issue

### ISSUE THREAD

**Issue by benitazz** [kekeh/ngx-mydatepicker#12]
HTML:

 <div class="panel-body form-horizontal">

     <div class="form-group">
         <label class="form-control-label col-md-4 col-lg-4">from</label>
        <div class="col-lg-8 col-md-8">
           <my-date-picker [options]="myDatePickerOptions" [(ngModel)]="fromDate"></my-date-picker>
        </div>
      </div>

      <div class="form-group">
         <label class="form-control-label col-md-4 col-lg-4 ">to</label>
         <div class="col-lg-8 col-md-8">
             <my-date-picker [options]="myDatePickerOptions" [(ngModel)]="toDate"></my-date-picker>
        </div>
      </div>
</div>

TS:
 this.myDatePickerOptions = {
      dateFormat: 'dd/mm/yyyy',
      showClearDateBtn: false,
      height: '48px',
      inline: false,
      alignSelectorRight: false
    };

Version:
 "mydatepicker": "^1.7.14",

Problem:

![image](https://cloud.githubusercontent.com/assets/3354516/24347059/5b897f14-12d7-11e7-83b8-c1678daa3207.png)

**Comment by kekeh** [comment]
I tried your code and it worked ok.

mydatepicker have **encapsulation: ViewEncapsulation.None** set which means it accepts styles also  outside from the component.

You have to inspect HTML and styles with inspector of the browser and disable style properties one by one to see which definition causes this issue.

Select date picker header (problem part) and select right mouse button and Inspect from the opened menu. Then disable styles one by one.

If you find a definition which causes the problem let me know.

**Comment by benitazz** [comment]
Busy with the inspection and will provide feedback as soon as I'm done

**Comment by benitazz** [comment]
Found the issue, someone added a global style whereby he set the min width of a button to 150px
