### ISSUE TITLE
NgxMyDatePickerDirective causes unnecessary AppView.detectChanges's at every click in the document for every element with this directive.

### ISSUE THREAD

**Issue by hailtondecastro** [kekeh/ngx-mydatepicker#120]
NgxMyDatePickerDirective causes unnecessary AppView.detectChanges's at every click in  #the document for every element with this directive.
  Although no bind has occurred, AppView.detectChanges can take considerable time in pages with many bindable elements.
  In "sample-date-picker-ngmodel.html" I changed it to create 18 NgxMyDatePickerDirective, the result of "document.click" can be seen in this images:
![schennshot-2018-01-04 14-11-11](https://user-images.githubusercontent.com/1711296/34576869-1800e244-f15e-11e7-876c-739e99364c19.png)
![schennshot-2018-01-04 14-11-27](https://user-images.githubusercontent.com/1711296/34576870-182705fa-f15e-11e7-9e00-9671edd589dc.png)
  I think this pullrequest solves that: [#119](https://github.com/kekeh/ngx-mydatepicker/pull/119)
  #119

**Comment by kekeh** [comment]
I merged your PR (#119). New version of the component is 2.4.1.
