### ISSUE TITLE
Replicate editableDateField, openSelectorOnInputClick options for ngx-mydatepicker

### ISSUE THREAD

**Issue by yanshuf0** [kekeh/ngx-mydatepicker#129]
I'm looking to use the appendSelectorToBody feature of this picker which is not present on mydatepicker but i also need editableDateField and openSelectorOnInputClick. Any recommendations?

**Comment by kekeh** [comment]
You can add click handler to input box and call the **openCalendar()** function as follows:

```html
<input ngx-mydatepicker [(ngModel)]="model" [options]="myDatePickerOptions" 
   #dp="ngx-mydatepicker" (click)="dp.openCalendar()" (dateChanged)="onDateChanged($event)"
   readonly />
```

You can also set input box read only like example above. Here is an example on what you can do: https://github.com/kekeh/ngx-mydatepicker/blob/master/examples/sample-date-picker-ngmodel/sample-date-picker-ngmodel.html
