### ISSUE TITLE
Can't change a "disabled" state of input element.

### ISSUE THREAD

**Issue by dmitrypaul** [kekeh/ngx-mydatepicker#13]
Seems placing an [disabled] attribute makes no affect on the element.
For example element: 
`<input ngx-mydatepicker ([ngModel])="someModel" [disabled]="true"/>`
will be active.

**Comment by kekeh** [comment]
You can try to use readonly instead:
<input ngx-mydatepicker ([ngModel])="someModel" [readonly]="true"/>

**Comment by dmitrypaul** [comment]
Thank you for the fast reply, 
unfortunately it does not work for me, I'm using a click event directly on the input element in order to toggle the calendar.

**Comment by kekeh** [comment]
You can try something like this:
```html
<input ngx-mydatepicker ([ngModel])="someModel" [readonly]="disable" 
    (click)="!disable&&toggeCalendar()"/>
```

```javascript
private disable = false;

disableInput(): void {
   this.disable = true;
}
```

toggleCalendar() function is called only if disable = false

**Comment by dmitrypaul** [comment]
Yes, it works this way. Thank you a lot :+1: 

But still I think it will be nice to fix it somehow in future. 
Thanks for the great plugin.

**Comment by kekeh** [comment]
I got disabled attribute working with the following way:
```html
<input ngx-mydatepicker ([ngModel])="someModel" [attr.disabled]="disabled?'':null"
    (click)="toggeCalendar()"/>
```
```javascript
private disabled = false;

// disable component
disableInput(): void {
   this.disabled = true;
}
```

**Comment by nicksterx** [comment]
This is a nice work around but it would be nice to be able to use the built in disable() and enable() methods in the form control model.
