### ISSUE TITLE
Question: (dateChanged) doesn't update form.controls['date'].value right away?

### ISSUE THREAD

**Issue by ryanbuening** [kekeh/ngx-mydatepicker#134]
I'm having an issue getting ngx-mydatepicker to update the form value on change. I have the following:

#### component.html

`<input ngx-mydatepicker name="date" [(ngModel)]="date" [options]="dateOptions" #date="ngModel" #dp="ngx-mydatepicker" (click)="dp.toggleCalendar()" (dateChanged)="onDateChange($event)" />`

#### component.ts

```
public onDateChange(event: IMyDateModel) {
	console.log("this.form.controls['date'].value= " + JSON.stringify(this.form.controls['date'].value));
}
```

When I select a new date, `this.form.controls['date'].value` contains the current value in the input, **not** the new chosen date.

Is there a callback/event I can use that waits until the form value is updated? I also tried the `inputFieldChanged` callback and it has the same behavior as above.

**Comment by kekeh** [comment]
Try to set your console.log inside the setTimeout in your onDateChange function. For example:
setTimeout(()=> {
    console.log....
});

**Comment by ryanbuening** [comment]
@kekeh thanks, that does work. Is this a common pattern in Angular to handle these types of scenarios?

**Comment by kekeh** [comment]
In javascript It is quite common pattern. I have used It in many place in Angular 1 development..
