### ISSUE TITLE
Disable day of week

### ISSUE THREAD

**Issue by ZuraM** [kekeh/ngx-mydatepicker#136]
how can i disable certain day of week? I see there is property for disabling weekends but what if i want to disable only Sunday

**Comment by kekeh** [comment]
Hi @ZuraM 

I added new option **disableWeekdays**. More info check documentation of that option: https://github.com/kekeh/ngx-mydatepicker#options-attribute

Example:
```javascript
myDatePickerOptions: INgxMyDpOptions = {
    // other options
    disableWeekdays: ['we', 'th']  // disable WEdnesdays and Thursdays
};
```

New version of the component is 2.4.5.
