### ISSUE TITLE
How to assign date format dd/MM/yyyy to ngx-mydatepicker control?

### ISSUE THREAD

**Issue by prakashkaruppiah** [kekeh/ngx-mydatepicker#137]
We have dateformat from database dd/MM/yyyy (28/03/2018) format as a string. How to assign this type of format to ngx-mydatepicker. Please help us.

**Comment by kekeh** [comment]
Hi @prakashkaruppiah 

Value of **dateFormat** must be given as lowercase so you have to convert the value of **dateFormat** to lowercase.
