### ISSUE TITLE
Prevent tab from "diving" into calendar

### ISSUE THREAD

**Issue by CelsoSantos** [kekeh/ngx-mydatepicker#14]
Hello,

It's pretty much like the title says, I have a use case where I want a tab press to navigate to the following input rather then navigating into the calendar components (which btw, is also navigating into the disabled elements, which, IMHO, shouldn't since they are disabled.

How can I prevent this behaviour?

I've tried to use `(keyup.tab)="change.emit()"` which is an `@Output` directive, which triggers the `(change)` event in the declaration:

myForm.html
```
<date-input [model]="mmkService.steps['descdate'].model" (focus)="goToId('descdate')" (change)="processDescription('descdate');"></date-input>
```

date-input.html:
```
<input class="mmkmaker datepicker ui-inputtext clickable" id="{{model.focusid}}" (click)="dp.toggleCalendar()" (focus)="dp.openCalendar()"
	    (blur)="dp.closeCalendar()" ngx-mydatepicker [(ngModel)]="selectedDate" [options]="dpOptions" #dp="ngx-mydatepicker" (dateChanged)="onSelect($event)"
	    (calendarToggle)="onCalendarToggle($event)" [readonly]="true" (keyup.tab)="change.emit()" />
```

date-input.ts
```
@Output() change = new EventEmitter();
@Output() focus = new EventEmitter();
```

**Comment by kekeh** [comment]
If you want to set focus to the specific input element the best way is to create directive like below:

```javascript
import { Directive, ElementRef, Renderer, AfterViewInit, Input } from "@angular/core";

@Directive({
    selector: "[mydpfocus]"
})
export class FocusDirective implements AfterViewInit {

    constructor(private el: ElementRef, private renderer: Renderer) {}

    ngAfterViewInit() {
        this.renderer.invokeElementMethod(this.el.nativeElement, "focus", []);
    }
}
```

```html
<input mydpfocus/>
```

**Comment by kekeh** [comment]
Closing this issue. You can reopen this issue if you have still same situation.
