### ISSUE TITLE
dateChanged not working as expected

### ISSUE THREAD

**Issue by AlwaysAbhl001** [kekeh/ngx-mydatepicker#142]
Hi , 

Thanks for your wonderful plugin.

I'm setting default date to my date picker as
`dsmodel: any = { date: { day: 16, month: 4, year: 2018 } };`

`.html`
```
<input class="form-control" placeholder="select a date" ngx-mydatepicker name="singledate"
                     [(ngModel)]="dsmodel" [options]="dsingleOptions" #dpsingle="ngx-mydatepicker" (dateChanged)="dpsingleChange($event)"/>
```

`.ts` file

```
dpsingleChange(event) {
      console.log("In Single Dp OnChange")
  }
```
What I'm expecting is after on an initial load my dateChanged function should be called so that I can check what ever value I have set is valid or not(or to do any other logic). but it fails to callback.

**Comment by kekeh** [comment]
Date picker validates a date internally. You can implement the **inputFieldChanged** callback. It is called when the value in the input field change. Callback has parameter [IMyInputFieldChanged](https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/interfaces/my-input-field-changed.interface.ts) which contain **valid** flag. It indicates is date valid or not.

Documentation: https://github.com/kekeh/ngx-mydatepicker#inputfieldchanged-callback

**Comment by AlwaysAbhl001** [comment]
@kekeh but when I manually change the input field both functions execute's. So can I achieve every thing in inputFieldChanged ? if so I'll replace dateChanged  call back with inputFieldChanged.

**Comment by kekeh** [comment]
The **inputFielChanged** callback is called every time when value of the input field changes. The **dateChanged** callback is called only when a date is selected, valid date is typed to input box or the date is cleared from the input box.

**Comment by AlwaysAbhl001** [comment]
@kekeh  probably out of topic, I fork, clone your project and followed your documentations made small changes in styles, build the bundle `ngx-mydatepicker-2.4.5.tgz` after installing this in local project I'm facing. how can I over come this ?
 ```
__WEBPACK_IMPORTED_MODULE_0__angular_core__.OpaqueToken is not a constructor
    at eval (location_strategy.js:54)
    at Object.../../../../ngx-mydatepicker/node_modules/@angular/common/src/location/location_strategy.js (vendor.bundle.js:1567)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (location.js:3)
    at Object.../../../../ngx-mydatepicker/node_modules/@angular/common/src/location.js (vendor.bundle.js:1543)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (index.js:1)
    at Object.../../../../ngx-mydatepicker/node_modules/@angular/common/index.js (vendor.bundle.js:1423)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (ngx-my-date-picker.module.js:2)
```

**Comment by AlwaysAbhl001** [comment]
@kekeh  Any update on this ? installing your package from npm works fine but for local bundle above error throws.

**Comment by AlwaysAbhl001** [comment]
@kekeh  Yea I followed those steps, let me do it freshly. And you did it in angular 5 ?
