### ISSUE TITLE
Change the calendar css skin

### ISSUE THREAD

**Issue by orphen92** [kekeh/ngx-mydatepicker#143]
Hi all,
i wouldlike change the css style of the calendar.
When i change .ngxmdp .caltable, my css is not recognized (not load).
How can i do that please?

Thank you

**Comment by kekeh** [comment]
It may be difficult to change style of component. One option is to create own version of the component. If you are willing to create own version you can start from here: https://github.com/kekeh/ngx-mydatepicker#development-of-this-component

You can can also check this: https://github.com/kekeh/mydatepicker/issues/118

**Comment by AlwaysAbhl001** [comment]
@orphen92 if you are trying to implement this in angular 5 and succeed, do share your solution here.
