### ISSUE TITLE
[Feature Request] - Refresh() method

### ISSUE THREAD

**Issue by firstdivision** [kekeh/ngx-mydatepicker#147]
In my app the calendar has different configurations depending on user interaction after the main component loads.  

Two things that might happen are the "disableDates" and "disableWeekdays" values changing.  If they do, the calendar needs to update itself to reflect these new restrictions.

Updating the Options property after the calendar has been built has no effect on the calendar that I've seen. Perhaps I'm missing an existing way to do this, either via the ngx-mydatepicker API, or in Angular itself?  

**Heres what I tried:**
```
  myOptions: INgxMyDpOptions = {
      dateFormat: 'mm/dd/yyyy'
  };

  model: any = { jsdate: new Date()};

  disableMondays(){
    console.log("disabling mondays...");
    this.myOptions.disableWeekdays = ["mo"];  
    //this.model = { jsdate: new Date("2017-01-01")}; //Maybe updating the model will strigger a UI update...
    console.log("disabled mondays");
  }

  loadNewInvalidDates(){
    var invalidJsDates: Date[] = [new Date("2018-05-09"), new Date("2018-05-29")];

    var datesForDisabled = invalidJsDates.map(d => <IMyDate>{ day: d.getDate(), month: d.getMonth() + 1, year: d.getFullYear()});
    this.myOptions.disableDates = datesForDisabled;
  }
```

Example app / my attempt here:  https://stackblitz.com/edit/angular-f2chrr?file=src%2Fapp%2Fapp.component.ts

**Comment by kekeh** [comment]
Hi @firstdivision 

You can change any option dynamically. You have to create copy of options at first and then change the value of the option. In order the datepicker detect the change a copy of option are needed. Here  is an example on how to dynamically change value of disableSince: https://github.com/kekeh/mydatepicker/wiki/Set-disableSince-option

Exampe is from the mydatepicker but same method works also with this component.

**Comment by firstdivision** [comment]
Aha!  That works, thank you!  I apologize if that was in the documentation somewhere and I missed it.
