### ISSUE TITLE
Access old value onInputFieldChanged()

### ISSUE THREAD

**Issue by thaihacong** [kekeh/ngx-mydatepicker#15]
Hi @kekeh, I am currently using your ngx-mydatepicker, and I would like to implement the feature that
- if a user inputs an invalid date into the input field, when the input blurs, I would revert the input back to its last valid value.

I tried both dateChanged() and onInputFieldChanged() callback, but none of them give me access to the old value. dateChanged() callback is not fired when user inputs invalid date. As I tried to debug, In this case, the IMyDate model has an empty value.
My reason to access the old date value in callback is to back up the last valid value, so, I can revert it easily when the input blurs.

Do you have any ideas to solve this problem.
Thank you very much.

**Comment by kekeh** [comment]
Hi @thaihacong 

You can try something like this:
```html
<input ngx-mydatepicker name="mydate" [(ngModel)]="model" [options]="myOptions"
    #dp="ngx-mydatepicker" (dateChanged)="onDateChanged($event)" (blur)="blurInput()"/>
```

```javascript
import {Component} from '@angular/core';
import {IMyOptions, IMyDateModel, IMyDate} from 'ngx-mydatepicker';

// here are other component related code

export class MyApp {
    private myOptions: IMyOptions {
        // options here...
    }

    private model: string = '';   // not initial date set
    private validDate: IMyDate = null;

    constructor() {}

    onDateChanged(event: IMyDateModel):void {
        // date selected
        if(event.formatted !== '') {
            // save valid date
            this.validDate = event.date;
        }
    }

    blurInput(): void {
        if(this.validDate !== null) {
            this.model = {date: this.validDate};
        }
    }
}
```
