### ISSUE TITLE
How to change global options ?

### ISSUE THREAD

**Issue by sozdemir82** [kekeh/ngx-mydatepicker#150]
we need change global options in module

**Comment by kekeh** [comment]
Hi @sozdemir82 

You can set global options as follows:
```ts
import {NgxMyDatePickerConfig} from 'ngx-mydatepicker';
// other imports here...

export class YourTestApp {

    constructor(private configService: NgxMyDatePickerConfig) { 
        configService.dateFormat = 'dd.mm.yyyy';
        configService.firstDayOfWeek = 'su';
        // and so on...
    }

}

**Comment by sozdemir82** [comment]
Thanks for your help 
but when I start the project I have a error about that >>> has no exported member 'NgxMyDatePickerConfig'

**Comment by kekeh** [comment]
There was a bug. Update the latest version 2.4.6 and try again.
