### ISSUE TITLE
Options not correctly update when changed in calendarViewChanged

### ISSUE THREAD

**Issue by kurushimeru** [kekeh/ngx-mydatepicker#153]
Hi,

My aim is to disable Christmas and New Year day. To do that dynamically, I wanted to update the disableDates options when the calendarView is changed :

```
<input ngx-mydatepicker name="mydate" #dp="ngx-mydatepicker" class="form-control"
    [(ngModel)]="selectedDate"
    [disabled]="!enableDatePicker"
    [(options)]="datePickerOptions"
    (calendarViewChanged)="changeDisabledDates($event)"
    (dateChanged)="selectedDateChanged()"/>
                        
<span class="input-group-addon btn-calendar-picker" (click)="dp.    
    <span class="fa fa-calendar"></span>
</span>
```

```
public enableDatePicker = true;
    public selectedDate = { jsdate: moment().toDate() };
    public datePickerOptions: INgxMyDpOptions = {
        dateFormat: 'yyyy-mm-dd',
        disableWeekends: true,
    };

    constructor(private auth: AuthService, private data: DataService) {
    }

    ngOnInit() {
        this.waitSpinner = new WaitingSpinComponent();
    }

    public selectedDateChanged() {
    }

    public changeDisabledDates(event: IMyCalendarViewChanged) {
        let options = JSON.parse(JSON.stringify(this.datePickerOptions));

        options.disableDates = [
            { year: event.year, month: 12, day: 25 },
            { year: event.year, month: 1, day: 1 }
        ];

        this.datePickerOptions = options;
    }
```

But there is two issues : 

- When you're already on december/january and try to go to january or december, it doesn't work properly. Christmas and new year are enabled. If you go to february/november and go back to january/december, it works properly.

- When you're already on december/january and try to change the year only, you have the same issue than above.

**Comment by kekeh** [comment]
Hi @kurushimeru 

I did some changes the **disableDates** option. It works now so that you can disable recurring dates. For example disable Christmas and new year of of every year you can set disableDates option as follows:

```javascript
    disableDates: [{year: 0, month: 12, day: 25}, {year: 0, month: 1, day: 1}]
```

Value of **year** or **month** can be zero. If the value of year/month is zero it affects all years/months.

Install the latest version **2.4.7**.
