### ISSUE TITLE
Regarding disableWeekends and enableDates

### ISSUE THREAD

**Issue by kurushimeru** [kekeh/ngx-mydatepicker#157]
Hi,

I would like to disableWeekends, but there is an exception : if the last day of the month is a week end, it needs to be enable. How can I do that ? I used kendo date picker before and there is a function so you can choose which day enabled/disabled.

Edit : for enableDates , is it possible as well to put "year: 0" ?

Thanks

**Comment by kekeh** [comment]
You can disable weekends by using the **disableWeekends** option.  Then you can use the **enableDates** option enable already the disabled dates.

You can limit the count of months to set **minYear** and **maxYear** options.

In version 2.4.8 it is possible to set zero value to year and month properties when using **enableDates** option.
