### ISSUE TITLE
[Feature request] Add highlightDates option and weekendHighlight option

### ISSUE THREAD

**Issue by thaihacong** [kekeh/ngx-mydatepicker#16]
Hi @kekeh, could you please add the `highlightDates` option and `weekendsHighlight` option to ngx-mydatepicker?

`weekendsHighlight` option would highlight both saturdays and sundays (similar to `sunHighlight`).
`highlightDates` option would highlight specific dates (similar to `enableDates`/ `disableDates`), for example, all national holildays in the date picker to the user.

**Comment by kekeh** [comment]
I added option **markDates** and **markWeekends**. More info read document of options: https://github.com/kekeh/ngx-mydatepicker#options-attribute

New version of the component is: 0.1.6

**Comment by thaihacong** [comment]
Hi @kekeh, thank you very much for your very fast response.

I've just got a new problem that I should highlight different sets of dates. For example: holidays in US should be green, holidays in Canada should be blue, ...

So, could you please make the css class for `markDates` option configurable? In addition, there would be different sets of dates to be highlighted using different css classes.

One proposal object type could be:
```
[
  {
    "cssClass": string,
    "markDates": Array<IMyDate>
  }
]

```

**Comment by kekeh** [comment]
I changed functionality of option **markDates** and **markWeekend**. More info read document of options: https://github.com/kekeh/ngx-mydatepicker#options-attribute

New version of the component is: 0.1.7

**Comment by thaihacong** [comment]
@kekeh: Thank you very much for your awesome work.

**Comment by thaihacong** [comment]
Hi @kekeh, sorry for bothering you in this topic again.
Currently, I am using both `sunHighlight` and `markWeekends` options in your component.
```
    sunHighlight: false,
    markWeekends: {
      marked: true,
      color: 'red'
    }
```

![ngx-mydatepicker](https://cloud.githubusercontent.com/assets/8019304/25615785/72b3da76-2f39-11e7-826c-58c4be80a325.png)
These two options together may make user confused. I would expect weekend days to have similar style (color: red) to Sundays.

Could you please add `weekendHighlight` option, and / or `datesHighlight` options so that I can easily manage this case?
Thank you.

**Comment by kekeh** [comment]
Why not set the sunHighlight option to false?

**Comment by thaihacong** [comment]
Of course, I can do this as a work around.
However, I still ask you to add the `highlight` options if possible when you have time.

**Comment by kekeh** [comment]
I added options **satHighlight** and **highlightDates**. 

First one highlight Saturday and second one can contain list of dates. More info from here: https://github.com/kekeh/ngx-mydatepicker#options-attribute

This change is in version 1.0.2.
