### ISSUE TITLE
Input is focused after month is selected

### ISSUE THREAD

**Issue by be-ndee** [kekeh/ngx-mydatepicker#162]
My input field is not disabled, so the user can insert a date in the input field. When the calendar is opened and a month is selected, the calendar closes and the input field is focused (on the iPad the keyboard will open). I think this is not a "nice" behaviour, because in most cases you don't want to change the date then in the input (my opinion ;-) ). Is it possible to change this behaviour?

**Comment by kekeh** [comment]
Hi @be-ndee 

I added new option **focusInputOnDateSelect**. Set it to **false** and input is not focused after a date select. This new option is in version 2.4.9.

**Comment by be-ndee** [comment]
Thank you, it's working!
