### ISSUE TITLE
Distinct legitimately empty value from misformatted value

### ISSUE THREAD

**Issue by vkopyl** [kekeh/ngx-mydatepicker#17]
Thanks a lot for such a great module, very convenient!

However, I found impossible to write a custom validator for **not** required date field, because in the both cases: no value and bad value, the FormControl.value is "".

**Comment by kekeh** [comment]
Hi @vkopyl 

There is callback **inputFieldChanged** which one parameter is **valid** and it indicates is the date valid in the input box. More info: https://github.com/kekeh/ngx-mydatepicker#inputfieldchanged-callback

You can implement this callback and you know if the date is valid or not.

You can test here: https://kekeh.github.io/ngx-mydatepicker

open console of the browser to see callback messages

Does this callback help?

**Comment by vkopyl** [comment]
Yes!  It helps. Not that "naturally" like other Validators, I still had to call setErrors myself, but the root problem solved.  Thanks a lot for your help!
