### ISSUE TITLE
disableUntil not disabling if parsed string is used

### ISSUE THREAD

**Issue by Hellogark** [kekeh/ngx-mydatepicker#175]
I'm trying to use current day values to disable all days before today, so first i'm getting the current date with `new Date();`  then assing year, month and day to a var

```
private currDate = new Date();
public day = this.currDate .getDate();
private month = this.currDate .getMonth();
private year = this.currDate .getFullYear();
```
then in myOptions im trying to set disableUntil values like this
  `  disableUntil: {year: parseInt(this.year.toString()), month: parseInt(this.month.toString()), day:parseInt(this.day.toString())}`
the previous month get blocked but the days don't

**Comment by kekeh** [comment]
https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

Check above link. It is from mydatepicker but works also with this component.

**Comment by Hellogark** [comment]
this date ` let d: date = new Date();` has to be changed to `let d: Date = new Date();`, somehow it works but it's strange because disableUntil interface accept a number  as value and i'm parsing strings to number. Thanks for the help, this is the only datepicker library that it works for me, it's awesome. Good work
