### ISSUE TITLE
Changing options dynamically

### ISSUE THREAD

**Issue by jls2933** [kekeh/ngx-mydatepicker#18]
I am trying to synchronize two date pickers, changing allowed dates in second one when a date is selected in the first one.
I am listening on dateChanged event in the first date picker, and updating options struct accordingly in second one, but with no success : second date picker ignores new options set.
Is options designed to be dynamic ?

**Comment by kekeh** [comment]
You need to create copy of options at first and then update the value. This example is from mydatepicker but it works also here: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

**Comment by ayyash** [comment]
Can this be a feature request?
```picker.options('disableUntil', newValue);```

**Comment by ayyash** [comment]
Actually what I attempted (and it works) is use the private **opts** property, why is it private? its amazing what you can do with it
