### ISSUE TITLE
datepicker in scrolling modal

### ISSUE THREAD

**Issue by Fatmahermessi** [kekeh/ngx-mydatepicker#186]
I have a problem with ngx-mydatepicker in a modal with scroll 
when I scroll in the modal and try to open the calendar it displays in a wrong location 
the datepicker is configured with a fixed position and z-index 10000

**Comment by kekeh** [comment]
Try to set style **position: relative** to the **parent element** of the **input box**.

**Comment by Fatmahermessi** [comment]
yes it's already configured that way

**Comment by kekeh** [comment]
Try to set the **appendSelectorToBody** option to **true**.

**Comment by Fatmahermessi** [comment]
it works Thank you
