### ISSUE TITLE
Calendar css is not loading correctly

### ISSUE THREAD

**Issue by reddyavi256** [kekeh/ngx-mydatepicker#19]
![calendar 1](https://cloud.githubusercontent.com/assets/27739671/25181084/588e9920-24de-11e7-8a22-21c4d6c9e857.PNG)
Hi,
I followed the steps that you provided and everything works perfect except the css of the calendar is not loading correctly while toggling both in IE11 and Chrome
![calendar](https://cloud.githubusercontent.com/assets/27739671/25181043/2e7acdc0-24de-11e7-9556-605deaced384.PNG)
. I attached the screenshot of this

**Comment by kekeh** [comment]
Can add here your dapicker options and input tag which contain ngx-mydapicker directive?

**Comment by reddyavi256** [comment]
I added custom class for Datepicker icon and custom input type tel where the size of text box will be according to our standards. I also have custom form validation with it. Please let me know if i am doing anything wrong ?

private myOptions: IMyOptions = {
        todayBtnTxt: 'Today',
        dateFormat: 'mm/dd/yyyy',
        firstDayOfWeek: 'mo',
        sunHighlight: true
    };

<div class="col-sm-4">
                            <div class="form-field">
                                <div class="font--denim"><label class="text" for="todate">Date Created To :</label></div>
                                <div>
                                    <input id="todate" class="date" style="float:none" placeholder="MM/DD/YYYY" maxlength="10" autocomplete="off" spellcheck="false" aria-label="Date. Please enter 2 digit month, 2 digit day, and 4 digit year" type="tel" ngx-mydatepicker name="todate"
                                           [(ngModel)]="model.todate" [options]="myOptions" data-validate="callback_date|required" [ngModelOptions]="{standalone: true}" #dp1="ngx-mydatepicker" />
                                    <button type="button" class="ui-datepicker-trigger" (click)="dp1.toggleCalendar()">
                                        <i class="glyphicon glyphicon-calendar"></i>
                                    </button>
                                    
                                </div>
                            </div>
                        </div>

**Comment by kekeh** [comment]
Add also input tag

**Comment by reddyavi256** [comment]
I added somehow it is missing. 

<div class="col-sm-4">
                            <div class="form-field">
                                <div class="font--denim"><label class="text" for="todate">Date Created To :</label></div>
                                <div>
                                    <input id="todate" class="date" style="float:none" placeholder="MM/DD/YYYY" maxlength="10" autocomplete="off" spellcheck="false" aria-label="Date. Please enter 2 digit month, 2 digit day, and 4 digit year" type="tel" ngx-mydatepicker name="todate"
                                           [(ngModel)]="model.todate" [options]="myOptions" data-validate="callback_date|required" [ngModelOptions]="{standalone: true}" #dp1="ngx-mydatepicker" />
                                    <button type="button" class="ui-datepicker-trigger" (click)="dp1.toggleCalendar()">
                                        <i class="glyphicon glyphicon-calendar"></i>
                                    </button>
                                    
                                </div>
                            </div>
                        </div>

**Comment by kekeh** [comment]
Your options are ok. Try this kind of simple input at first to see if it fix the problem and then add other attributes to the input:

```html
<input class="date" style="float:none" ngx-mydatepicker name="todate" 
    [(ngModel)]="model.todate" [options]="myOptions"  #dp1="ngx-mydatepicker" />
```

I don't know what is the problem. It worked ok in my test. Is there any errors on the console of the browser?

**Comment by kekeh** [comment]
There is some problems with IE11. Try here: https://kekeh.github.io/ngx-mydatepicker/

it doesn't set initial date and opening calendar takes long time.

**Comment by reddyavi256** [comment]
Thanks for your quick response on this issue.
Yes seems like there is some problem with IE11. I tried with the simple input control you mentioned in Chrome but it didn't resolve my issue. I was not able to view- year, month and today icon in the calendar and also the alignment is breaking

**Comment by kekeh** [comment]
I was able fix IE11 problem downgrading Angular 4.0.2 to 2.2.4

**Comment by kekeh** [comment]
You can try to run example application: https://github.com/kekeh/ngx-mydatepicker#development-of-this-component

**Comment by reddyavi256** [comment]
Any update on this issue? I am using Angular 4 and i am still having the same issue with the steps you provided. I dont know where the problem is. Could you please help me fixing this issue?

**Comment by kekeh** [comment]
I don't know what is the problem but you can try the following things:
1. reinstall package
  - npm remove ngx-mydatepicker
  - npm install ngx-mydatepicker@0.1.13 --save
2. inspect ngx-mydatepicker css with a browser
  - it is possible that external css of your project breaks the date picker styles
  - try to inactivate them one by one to see if it helps
  - it is possible that there is global button related style definition somewhere
  - right click empty month label and select **Inspect**. Month label is button element

Anyone else haven't reported this kind of error.

**Comment by kekeh** [comment]
Did you find a solution?

**Comment by kekeh** [comment]
I close this issue because no answer.
