### ISSUE TITLE
QUESTION: Does the datepicker support HH:mm format?

### ISSUE THREAD

**Issue by chriseenberg** [kekeh/ngx-mydatepicker#2]
Hi.

Your project looks great, how ever i have a use case where i need to add hours and minutes to the date stamp. Is this possible with your module? I haven't been able to find anything looking through the documentation, other than the user being able to specify a date format.

Kind regards - Chris

**Comment by kekeh** [comment]
Unfortunately this is only date picker and does not support hours and minutes.

**Comment by chriseenberg** [comment]
Okay thank you for your reply :)
