### ISSUE TITLE
Calendar Icons issue (::before content not displays Icons)

### ISSUE THREAD

**Issue by hevans90** [kekeh/ngx-mydatepicker#22]
Hi, thanks for the awesome plugin - the API is great.

I've been trying to get my head around this issue: 

![image](https://cloud.githubusercontent.com/assets/12142999/25488497/14eaa2cc-2b5f-11e7-8890-904f28c8217b.png)

As you can see some of the icons are not being displayed properly - I think this may have something to do with the 'font-family' property not being applied properly.

This is a peek at the css on one of the incorrectly displayed icons:

![image](https://cloud.githubusercontent.com/assets/12142999/25488581/4d0b0660-2b5f-11e7-8489-de751c8880ad.png)

Any ideas?

Cheers

**Comment by kekeh** [comment]
You can try to add the following to your css file:

```css
.ngxmdp .ngxmdpicon:before { 
    font-family: ngx-mydatepicker !important; 
}
```

**Comment by hevans90** [comment]
So I fixed the issue, turns out it was a compatibility issue with [@swimlane/ngx-datatable](https://github.com/swimlane/ngx-datatable ) because their font-family selector was overriding this:

![image](https://cloud.githubusercontent.com/assets/12142999/25489101/c2932f1a-2b60-11e7-8a8c-e07d682580bd.png)

To fix, I applied the following global (SCSS) style to my app:

![image](https://cloud.githubusercontent.com/assets/12142999/25489138/db0b7390-2b60-11e7-9204-07cc4afce434.png)
