### ISSUE TITLE
Expression has changed after it was checked error

### ISSUE THREAD

**Issue by Bigless27** [kekeh/ngx-mydatepicker#23]
I keep getting the `Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.` whenever I use the `dp.toggleCalendar()` method. I've pin pointed it down to that expression. I've also attached a code sample below to show exactly how I'm using it. Any help would be great!
```
<label radio-enter>
	<input 
		type="radio"
		name="dateOption"
		formControlName = 'dateOption'
		value = 'other'
		(click)="dp.toggleCalendar()"
	/>
	<span>
	         <div>1</div>
	</span>
</label>

<input class="form-control" style="float:none;
 display: none"  ngx-mydatepicker name="date" [options]="myOptions"
 #dp="ngx-mydatepicker"
/>
```

**Comment by kekeh** [comment]
I am not able to reproduce but I did one fix. Update to the latest version **0.1.14**.

**Comment by Bigless27** [comment]
After digging deeper I found that the error checking is what's actually causing the error message display. Sorry I thought it was `dp.toggleCalendar()` earlier! Checking the form for a status like touched looks like it's most likely causing it. Here is a code example. Also, thanks again for your prompt response!
```
<div [formGroup]='startForm' novalidate>
  <label radio-enter>
	<input 
	type="radio"
	name="dateOption"
	formControlName = 'dateOption'
	value = 'other'
	(click)="dp.toggleCalendar()"
	/>
	<span>
		<div class="flex-container-column">
			<div></div>
		</div>
	</span>
</label>
    <div *ngIf="startForm.get('dateOption').errors && (startForm.dirty || startForm.touched)">
    	<span><i class = 'icon icon-warning error-message'></i></span>
        <span class="error-message" *ngIf="startForm.get('date').errors.required">
            Required
        </span>
    </div> 
	<input class="form-control" style="float:none; display: none"  ngx-mydatepicker name="date" [options]="myOptions" #dp="ngx-mydatepicker"/>
</div>
```
