### ISSUE TITLE
editableMonthAndYear option removed in version 1.0.0

### ISSUE THREAD

**Issue by kekeh** [kekeh/ngx-mydatepicker#25]
Option **editableMonthAndYear** removed. Added options **monthSelector** and **yearSelector**. By default the **monthSelector** and the **yearSelector** are **true**.

If **monthSelector** is **true** a list of months is shown if a month label is clicked. For example:

![month-selector](https://cloud.githubusercontent.com/assets/11028839/25616565/37754082-2f46-11e7-8027-f131e3d088a5.png)

If **yearSelector** is **true** a list of years is shown if a year label is clicked. For example:

![year-selector](https://cloud.githubusercontent.com/assets/11028839/25616568/3ffc7ea0-2f46-11e7-844a-c30cd2123cbe.png)

You can set both values to false if you don't need this kind of feature.

You can test functionality here: http://kekeh.github.io/ngx-mydatepicker/

**Comment by thaihacong** [comment]
I've just did a quick test.

There is a bug that if I click anywhere in `<td colspan="5" class="yearchangebtncell"></td>` except the button, then the datepicker is closed.

**Comment by kekeh** [comment]
True. I fixed it in version 1.0.1.

**Comment by thaihacong** [comment]
Hi @kekeh, currently, I need to enable only some specific dates.
So, I set my dateOptions as follow
```
      minYear: 1900,
      maxYear: 2099,
      disableSince: {
        year: 1900,
        month: 1,
        day: 1
      },
      enableDates: [
        {
          year: 2017,
          month: 5,
          day: 1
        },
        {
          year: 2017,
          month: 4,
          day: 30
        }
      ]
```

The dates in date-picker are now enabled and disabled correctly.

However, the `next month` and `next year` buttons are disabled.
![ngx-mydatepicker-1](https://cloud.githubusercontent.com/assets/8019304/25660167/5599ae20-300b-11e7-9ce1-bae5eba76521.png)

The month selections are all disabled as you can see in the picture. With my current options, I would expect `Apr` and `May` to be enabled.
![ngx-mydatepicker-2](https://cloud.githubusercontent.com/assets/8019304/25660169/559de3e6-300b-11e7-926c-318a63a5e519.png)

All year selections are also disabled. `2017` should be enabled in this case.
The `scroll down` button also does not work.
![ngx-mydatepicker-3](https://cloud.githubusercontent.com/assets/8019304/25660168/559d6e70-300b-11e7-8c30-a32dc19d1421.png)

**Comment by kekeh** [comment]
There is option **disableHeaderButtons** and it is **true** by default (read documentation of **disableHeaderButtons**). That is why next buttons are disabled. Set it to **false**. Month and years in their selector are disabled all because you are using **disableSince** from the beginning of 1900.

You can remove the **disableSince** and use:

**disableDateRanges**: [{begin: {year: 1900, month: 1, day: 1}, end: {year: 2099, month: 12, day: 31}}]

probably then months and years are not disabled

**Comment by thaihacong** [comment]
I tried your suggestion with `disableDateRanges`. Now, it works as expected. I keep `disableHeaderButtons` as default (true).

I also tried my old options again, and I found that the previous month and previous year buttons always work. I could go to (old) months or years which do not contain any selectable dates.
![ngx-mydatepicker-4](https://cloud.githubusercontent.com/assets/8019304/25663325/a5abebc4-3017-11e7-8a61-86693c00e4b8.png)

Could you please look at this again?

**Comment by kekeh** [comment]
If you use disableUntil and disableHeaderButtons is true and previous month is fully disabled by disableUntil previous button is also disabled.

If you use disableSince and disableHeaderButtons is true and next month is fully disabled by disableSince next button is also disabled.

Previuos and next buttons are also disabled if you use minYear and maxYear. The disableHeaderButtons options does not affect minYear and maxYear.

**Comment by thaihacong** [comment]
I got your idea.

How about the case `disableSince and disableHeaderButtons is true and *previous month*' is fully disabled by disableSince`, should the `previous month` button be disabled in this case?

**Comment by kekeh** [comment]
Normally with disableSince you disable future dates. That is why only next buttons are disabled. With disableUntil you disable past dates. That is why only previous buttons are disabled.

**Comment by CaptianCold** [comment]
Even i am facing the same issue , my scenario is i am using disable until till a particular date and then i am manually enabling a specific date in previous month using enableDates property. In this case i expect the previous month button to be enabled since the previous month has a enabled entry.

I tried using the disableDateRanges , but that enables the previous button for all the months which i do not want
