### ISSUE TITLE
Datepicker as Shared component??

### ISSUE THREAD

**Issue by ymallikreddy521** [kekeh/ngx-mydatepicker#26]
Hi,

I created datepicker as shared component. 

I am finiding difficulty in passing the Options for each instance.

For example: On a page I have two picker shared components
 control 1:   <fw-date-picker ></fw-date-picker>
  control 2: <fw-date-picker ></fw-date-picker>

I want first control weekends to be disable and the second control to show all enable.

Can you suggest your thoughts in implementation.

Thanks

**Comment by kekeh** [comment]
You can set own options to both date pickers like here in mydatepicker example: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

**Comment by ymallikreddy521** [comment]
Thanks lot.

I am getting below error

  <fw-date-picker [options]="startDate"></fw-date-picker>
Can't bind to 'options' since it isn't a known property of 'fw-date-picker'.

**Comment by kekeh** [comment]
You should use input element for example:
```html
<input ngx-mydatepicker name="mydate" [(ngModel)]="model" [options]="startDate" 
    [defaultMonth]="defMonth" #dp="ngx-mydatepicker" (dateChanged)="onDateChanged($event)" />
```

Here is an example: https://github.com/kekeh/ngx-mydatepicker/tree/master/examples/sample-date-picker-ngmodel

**Comment by ymallikreddy521** [comment]
Thank you.

The solution you provided is on control. 

can't we set on the shared component.

Also can I disable the control which is in shared component.

**Comment by kekeh** [comment]
What do you mean shared component?

Here is an example on how to disable input box: https://github.com/kekeh/ngx-mydatepicker/issues/13

**Comment by ymallikreddy521** [comment]
Hi,

I placed all below code in component called - fw-date-picker
 <div class="input-group">
        <input class="datePicker_TextField" style="float:none;" placeholder="(mm/dd/yyyy)"  ngx-mydatepicker name="mydate" [options]="myOptions" #dp="ngx-mydatepicker" 
        (dateChanged)="onDateChanged($event)" (inputFieldChanged) ="onInputFieldChanged($event)"/>

        <span class="input-group-btn">
            <img ID="imgLink" class="btn btn-default" src="public/assets/img/Picker.gif" (click)="dp.toggleCalendar()"/>
        </span>
    </div>

and I am using the component

<fw-date-picker [options]="startDate"></fw-date-picker>

Now if I want to disable the component, how can I do.

Any ideas are much appreciated.

**Comment by kekeh** [comment]
Maybe you have to put image to button and disable button.

**Comment by ymallikreddy521** [comment]
Hey,

i fixed the problem.

<fw-date-picker [options]="startDate">

 @Input() public startDate: IMyOptions;

Thanks lot for all your help.

Control looks great. Thanks again
