### ISSUE TITLE
Stop "calendar closed" by date select

### ISSUE THREAD

**Issue by meenakshik-optimus** [kekeh/ngx-mydatepicker#27]
How can I restrict the close event of the calendar when a user selects a date.

**Comment by kekeh** [comment]
It is not an option. It always close calendar. If you need this kind of functionality you have to do code changes. You can start from here: https://github.com/kekeh/ngx-mydatepicker#development-of-this-component

One alternative is use mydatepicker as inline mode. Here is repository: https://github.com/kekeh/mydatepicker

an online demo is here: http://kekeh.github.io/mydatepicker/#inlinemode

**Comment by kekeh** [comment]
Hi @meenakshik-optimus 

I added new option **closeSelectorOnDateSelect** which default is **true**. Set it to **false** and a date select do not close the calendar. You can dynamically change the value of this option.

This is implemented in version 2.0.5.

**Comment by meenakshik-optimus** [comment]
Hey @kekeh , thanks for adding the option. As suggested by you, I have created my own component as I need to add some more features in the calendar. **ngx-mydatepicker** was really helpful for me. Thank you so much.
