### ISSUE TITLE
Specify value for the component as JavaScript Date

### ISSUE THREAD

**Issue by slavafomin** [kekeh/ngx-mydatepicker#28]
Hello!

Thank you for this great component!

However, is it possible to specify value for the component an standard JavaScript date? Right now, I have to manually convert the value every time when I need to set it:

```ts
private dateToMyDate (date: Date) {
  if (!(date instanceof Date)) {
    return { date: null };
  }
  return {
    date: {
      year: date.getFullYear(),
      month: date.getMonth() + 1,
      day: date.getDate()
    }
  };
}
```

What is the reasoning for using some custom date object (`IMyDate`) instead of a standard one (`Date`)?

Also, I can't use `dateToMyDate` interface to hint return value for my `dateToMyDate()` function because it expects all four properties to be set (i.e. `date`, `jsdate`, `formatted` and `epoc`). Is it possible to mark them as optional?

Thanks!

**Comment by kekeh** [comment]
Currently if you set initial value it must be in the [IMyDate](https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/interfaces/my-date.interface.ts) format. Maybe I have fix this that it also accepts javascript date object.

When the date is selected value of model is [IMyDateModel](https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/interfaces/my-date-model.interface.ts). You can take **jsdate** property from it which is a javascript date object.

**Comment by slavafomin** [comment]
Thanks. I think that from the implementation perspective it would be better to use `Date` objects everywhere cause it's a standard way for handling dates in JavaScript. No need to create extraneous formats for this. Maybe as a bonus it should also support `moment` instances, cause this is also a very popular library.

**Comment by kekeh** [comment]
You can now initialize with property of **jsdate**. For example when using **ngModel binding**:
```html
<input ngx-mydatepicker name="mydate" [(ngModel)]="model" [options]="myOptions" 
    #dp="ngx-mydatepicker" autocomplete="off"/>
```

```javascript
private model: Object = {jsdate: new Date()};   // initialized today with jsdate property
```

or when using **reactive forms**:
```html
<input ngx-mydatepicker name="mydate" formControlName="myDate" [options]="myOptions" 
    #dp="ngx-mydatepicker" autocomplete="off"/>
```
```javascript
this.myForm = this.formBuilder.group({
    // initialized today with jsdate property
    myDate: [{jsdate: new Date()}, Validators.required] 
});
```

That is all. I don't want create dependency to the moment library.

Update to the latest version 2.0.2.

**Comment by slavafomin** [comment]
@kekeh Thanks!

I've split the idea of using Date directly to the separate issue #30.
