### ISSUE TITLE
Bug: Selected date is not marked on repeated calendar opening

### ISSUE THREAD

**Issue by MrQwert** [kekeh/ngx-mydatepicker#37]
Hi,
First of all thank you for your hard work and such a nice plugin.

There's a small problem with it.
Once I select a date and close the calendar I want it to be marked the next time I open the calendar.
The [example](https://kekeh.github.io/ngx-mydatepicker/) works well but not my application.

Here's the code:

```
<input
       class="form-control" ngx-mydatepicker [(ngModel)]="selectedDate"
       [options]="myDatePickerOptions" #dp="ngx-mydatepicker"
       (click)="dp.toggleCalendar()"
       (dateChanged)="onDateChanged($event)" (calendarToggle)="onCalendarToggle($event)"
/>
```

```
  public myDatePickerOptions : INgxMyDpOptions = {
    dateFormat: "dd mmm",
    showSelectorArrow: true,
    sunHighlight: false,
    //closeSelectorOnDateSelect: false
  };

  public selectedDate;
```
There was the same problem before you added the `closeSelectorOnDateSelect` option.

Please let me know if you need any more information.

**Comment by kekeh** [comment]
You have invalid date format. Format without a year is not supported. Change format to **dd mmm yyyy**.

If this does not help let me know.

**Comment by MrQwert** [comment]
I need exactly this format to be displayed in the input field.
How can I achieve this in the most clear and easy way?
