### ISSUE TITLE
Disable past dates.

### ISSUE THREAD

**Issue by lakhvir1994** [kekeh/ngx-mydatepicker#39]
I just want to disable all dates before today's date by default & without passing { day: 22, month: 11, year: 2016 } dynamically to disableUntil.
My second question is that how to get today's date in typescript file without clicking the datepicker?

**Comment by kekeh** [comment]
Here is an example: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

It is from mydatepicker but it works also with ngx-mydatepicker.

**Comment by vinayistar** [comment]
There is no documentation for ngx-mydatepicker. Its not working when doing same as mentioned in https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option
