### ISSUE TITLE
"export 'IMyOptions' was not found in 'ngx-mydatepicker'

### ISSUE THREAD

**Issue by slavafomin** [kekeh/ngx-mydatepicker#40]
Hello!

I'm referencing `IMyOptions` interface in my code and I'm getting this warning: `"export 'IMyOptions' was not found in 'ngx-mydatepicker'` during compilation.

When I `ctrl+click` on the `IMyOptions` interface in my IDE, I can easily get to it's definition, so it's resolved correctly in IDE, but not by compiler. What could be the problem?

Thank you!

**Comment by slavafomin** [comment]
I can't completely comprehend the issue and to provide a solution, but here's the comment by **filipesilva** with detailed explanation of the actual problem: https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897.

**Comment by slavafomin** [comment]
Looks like we can't use decorated properties with the interfaces imported from other files, so this construct will throw this warning: `@Input() options: IMyOptions;`. And it looks like we can't do anything about this from our side. So the solution is to either re-define the interface in client code or to avoid such constructs.

**Comment by kekeh** [comment]
I am not able to reproduce but can you try to add:

```javascript
export * from "./dist/index";
```
to the **node_modules/ngx-mydatepicker/index.js** file. Remove other lines from the file. If warning disappears let me know.

**Comment by kekeh** [comment]
This https://github.com/kekeh/ngx-mydatepicker/tree/gh-pages is an angular-cli project and with the latest date picker 2.0.7 I am not able to reproduce.

Can you see the warning when you run **ng serve** command?

**Comment by slavafomin** [comment]
After adding exports from your comment: https://github.com/kekeh/ngx-mydatepicker/issues/40#issuecomment-302682364. The error actually disappeared.

**Comment by kekeh** [comment]
I have fixed this issue in version **2.0.9**.

**Comment by slavafomin** [comment]
Thanks )
