### ISSUE TITLE
Day-style

### ISSUE THREAD

**Issue by leomayer** [kekeh/ngx-mydatepicker#46]
Is there a chance to style the different days of the week with different background-colors? e.g. on Sat I want to have it light-blue, while on Sun light-red, for both the text color as black.

Since I don't see a specific class for the weekdays as style I have no clue how to configure it individually...

**Comment by kekeh** [comment]
**satHighlight**: set red color to Saturdays
**sunHighlight**: set red color to Sundays
**markDates**: mark any dates on colored circle
**markWeekends**: mark weekends on colored circle

You can test markDates option here: https://kekeh.github.io/ngx-mydatepicker

select mark today and open calendar.

All options: https://github.com/kekeh/ngx-mydatepicker#options-attribute

You can also develop own version of the component: https://github.com/kekeh/ngx-mydatepicker#development-of-this-component

Maybe I have to add option to set separate colors to each weekdays.
