### ISSUE TITLE
[Feature request] datepicker default date

### ISSUE THREAD

**Issue by daveriedstra** [kekeh/ngx-mydatepicker#47]
I would like to be able to select the default date / month / year for the datepicker, or have it open to something within the enabled range (ie, between `disableUntil` and `disableSince` or between `minYear` and `maxYear`).

My current use for the plugin is as an input for date-of-birth with a minimum age of 18. Here's the input process:
- (input begins empty)
- **focus** input field 
- datepicker opens to `currentMonth` -- _all options are disabled_
- **click** year select
- year select opens with a range of `currentYear` to `currentYear + 25` -- _all options are disabled_
- **click** year change up button
- range is now `currentYear - 26` to `currentYear - 1`. Only 8 options are enabled.
- if user is 26 or older, **click** year change up button
- **select** a year
- continue **selecting** month and date

So as you can see, setting an appropriate default date for the datepicker would save a lot of friction in this (and I'm sure other) cases.

Thanks for a great component!

**Comment by kekeh** [comment]
I don't know what you mean by default date, but it is already possible to set initial date.
- using ngModel binding: https://github.com/kekeh/ngx-mydatepicker#1-ngmodel-binding
- using reactive forms: https://github.com/kekeh/ngx-mydatepicker#2-reactive-forms

Or if you want to set default month: https://github.com/kekeh/ngx-mydatepicker#defaultmonth-attribute

**Comment by daveriedstra** [comment]
defaultMonth is exactly what I was looking for, I was just looking for it on IMyOptions and not as an attribute. Thanks & sorry to waste your time!

**Comment by arunmohan12345** [comment]
In year selector 2018 (current year) is coming first(2018 - 2042).I want to show 1994 to 2018 in default year view.Is it possible?Please help me !

**Comment by kekeh** [comment]
Hi @arunmohan12345 

You can try the defaultMonth attribute: 
https://github.com/kekeh/ngx-mydatepicker#defaultmonth-attribute
