### ISSUE TITLE
Date Validation 

### ISSUE THREAD

**Issue by AndriiDidkivsky** [kekeh/ngx-mydatepicker#51]
Hi, I've found strange behavior.  

Date validity checks only in [keyup host listener](https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/ngx-my-date-picker.input.ts#L81)

I have issue where I should set date from predefined list by choosing in the dropdown and date can't be in future. 
So I change my date with NgControl.setValue and IMyInputFieldChanged says me that date is valid but it is in the future. 

I've tried to run Host listener manualy with ViewChild, I've try to run Change detection and form.updateValueAndValidity. Just nothing. 
It's just one little example. I hope you'll understand what I mean. It happens in few other cases. 

Are you planning any workarounds or fixes in future ?

**Comment by kekeh** [comment]
If you set date value by the **setValue()** function it calls the **writeValue()** function in the background. I added validation of date also to the writeValue() function: https://github.com/kekeh/ngx-mydatepicker/blob/master/src/ngx-my-date-picker/ngx-my-date-picker.input.ts#L151

now the **inputFieldChanged** callback is called right value (false) if you call setValue() function with invalid date value (future date).

This change is in version: **2.0.11**.

Let me know if there is any problem.

**Comment by AndriiDidkivsky** [comment]
@kekeh ,great. We are using 2.0.10 now. I am trying to update and let you know.

**Comment by AndriiDidkivsky** [comment]
@kekeh, it's working.
Thanks for quick support. I'm closing issue.

**Comment by gavsmith43** [comment]
Hi, I'm having a similar issue using reactive forms. Setting the value like:

`this.myForm.setValue({
   startDate: dateConverter(this.formValues.startDateString),
});`

However I think this may be more related to the disabled dates. On the the constructor I disableUntil "yesterday" and if the loaded value is before that then it's not valid. Even if I reset using disableUntil "day before loaded value".

Any help would be appreciated.

Regards
Gav

**Comment by kekeh** [comment]
Hi @gavsmith43 

All disabled dates are not valid dates and then the **valid** flag of the **inputFieldChanged** is false.

How do you reset the **disableUntil** value?
