### ISSUE TITLE
Invalid date not flagging if field is not required

### ISSUE THREAD

**Issue by MGursoy** [kekeh/ngx-mydatepicker#52]
Hi, 

I've come across an issue whereby if the date field does not have a required validator, then a user can type in an invalid date but receive no warning. Then when the form is submitted, the date get's submitted with a blank value as the form value is only populated once valid.

**Comment by kekeh** [comment]
You can use **inputFieldChanged** callback: https://github.com/kekeh/mydatepicker#inputfieldchanged-callback. It indicates if the typed date is valid or not.

You can test it here: https://kekeh.github.io/ngx-mydatepicker

open console of the browser to see result of inputFieldChanged callback.
