### ISSUE TITLE
yearSelector option not working

### ISSUE THREAD

**Issue by ramoncarreras** [kekeh/ngx-mydatepicker#55]
Hi,
when I try to disable year selector with the following code...

    private myOptions: INgxMyDpOptions = {        
        yearSelector: false,
        dateFormat: 'dd.mm.yyyy',
    };

... it is still visible.

Can you check this out, please?

Thanks

**Comment by kekeh** [comment]
I tested it and it is worked ok. The **yearSelector** option means is year number is clickable or not. See image below.


![picker1](https://user-images.githubusercontent.com/11028839/27425803-4978afe8-5742-11e7-9f8f-0c5a5fea9425.png)

if **yearSelector** is **true** and year number is clicked the year selector is opened. See image below.

![picker2](https://user-images.githubusercontent.com/11028839/27425809-4d80d11a-5742-11e7-90ad-4856b3040388.png)

if **yearSelector** is **false** the year number is not clickable and the the year selector is not opened when it is clicked.

If you are using old version update the latest version (2.0.12) at first.
