### ISSUE TITLE
Bug: Incorrect position in .form-inline

### ISSUE THREAD

**Issue by chi-lee** [kekeh/ngx-mydatepicker#56]
Background: I use "ngx-mydatepicker" directive on an input element which is inside a form with class "form-inline" from bootstrap 4. The date picker is incorrectly positioned.
![screen shot 2017-06-27 at 12 18 38 am](https://user-images.githubusercontent.com/7223375/27549347-3e63d990-5ace-11e7-8c0b-0928296cdb23.png)

Reason: <ngx-my-date-picker> is appended to the element which uses the "ngx-mydatepicker" directive.

Suggestion: Insert <ngx-my-date-picker> before the element which uses the "ngx-mydatepicker" directive. Adjust "div.ngxmdp"'s position with css "top: {{inputElement.height}}"

**Comment by kekeh** [comment]
What happens if you set **float: none** style to your input box?

**Comment by chi-lee** [comment]
It doesn't help. I also added a few .input-group-btn and .input-group-addon, this further complicates the case.

Here's a code snippet:
```
<div class="input-group mr-2 mb-2">
  <span class="input-group-addon">{{'TIMETABLE.START' | translate }}</span>
  <input class="form-control" style="float:none" placeholder="e.g. 2017-06-29" ngx-mydatepicker name="startDate" [(ngModel)]="startDateModel" [options]="startDatePickerOptions" #startDatePicker="ngx-mydatepicker">
  <span class="input-group-btn">
    <button class="btn btn-secondary" (click)="startDatePicker.clearDate()">
      <i class="fa fa-times"></i>
    </button>
  </span>
  <span class="input-group-btn">
    <button class="btn btn-secondary" (click)="startDatePicker.toggleCalendar()"> 
      <i class="fa fa-calendar-o"></i>
    </button>
  </span>
</div>
```

**Comment by wisnuaryadipa** [comment]
I have same issue. 
btw float: none doesn't help

**Comment by Berno** [comment]
@chi-lee I had the same issue. I tried to set  position absolute to element ngx-my-date-picker adjusting the top attribute on ".ngxmdp .selector" and works.

**Comment by kekeh** [comment]
It is because **display** type of **input-group** in bootstrap 4 is **flex**. In bootstrap 3 it was **table**.

**Comment by kekeh** [comment]
I fixed this bug. I didn't test the fix with bootstrap 4 but it should work also with it. New version of the component is 2.1.0
