### ISSUE TITLE
Using moment and ngx-mydatepicker

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [kekeh/ngx-mydatepicker#57]
Hi,
Can I use moment & ngx-mydatepicker together.
Like some of the formats YY.MM.DD do not work with this component but they are formatted in moment.js

**Comment by kekeh** [comment]
If you want to include the moment.js to date picker you have to do code changes to date picker.

**Comment by aditya-padhi-kbl** [comment]
@kekeh 
May be we can start a new project and integrate datepicker with moment so that it will support localization and all date formats
