### ISSUE TITLE
ngx-mydatepicker with toggle button in a #ngFor loop

### ISSUE THREAD

**Issue by radams0x** [kekeh/ngx-mydatepicker#59]
Hi @kekeh,

For the button to toggle calendar, they are tied together with #dp:
input:  #dp="ngx-mydatepicker" 
button:  (click)="dp.toggleCalendar()

When I have a second date picker, I must name it something else, like #dp2:
input:  #dp2="ngx-mydatepicker" 
button:  (click)="dp2.toggleCalendar()

Or else the button toggles the wrong date picker. My problem is I am trying to use this in a template in a *ngFor loop; is there a way to dynamically wire in the toggleCalendar() call? I couldn't figure out how to dynamically set the attribute name, such as #dp-i where i is the current *ngFor index.

Thanks!!!

**Comment by kekeh** [comment]
You need a local variable in the input box to call functions of component even you do call from typescript.

I don't know other way to call functions.
