### ISSUE TITLE
model occasionally stale

### ISSUE THREAD

**Issue by daveriedstra** [kekeh/ngx-mydatepicker#6]
First, thanks for a very useful component.

It's possible for `ngx-mydatepicker` to be in a state where the formControl value doesn't match the input content. This happens when a user selects a date value successfully via the calendar input, then selects the text in the input element, deletes it with backspace/delete, and clicks outside of the component to blur it. 

![ngx-mydatepicker-issue](https://cloud.githubusercontent.com/assets/3504098/24066478/37d42000-0b30-11e7-82bb-68a45e699d41.gif)

This bypasses `Validators.required`, and maybe others. A dirty fix is to create a function like the following and register it to `(blur)`, but it's not ideal.

```typescript
maybeClearDatepicker(dp: NgxMyDatePickerDirective, inputEl: ElementRef, ctrlName: string) {
	if (!inputEl.nativeElement.value && !!this.formGroup.get(ctrlName).value) 
		dp.clearDate();
}
```

_Edit: corrections to workaround function_

**Comment by kekeh** [comment]
Thanks! I fixed this bug in version 0.0.9. Update to version 0.0.9.
