### ISSUE TITLE
Set button IDs for previous/next month/year?

### ISSUE THREAD

**Issue by KSuttle-cng** [kekeh/ngx-mydatepicker#60]
Is it possible to set the IDs of the buttons that trigger next|previous month|year ?

**Comment by kekeh** [comment]
Not possible. But you can create own version. You can start from here: https://github.com/kekeh/ngx-mydatepicker#development-of-this-component

**Comment by KSuttle-cng** [comment]
Ok then. Thanks for the quick response.
