### ISSUE TITLE
Touched property is not managed

### ISSUE THREAD

**Issue by Skrytch** [kekeh/ngx-mydatepicker#61]
Hi!

When the input lost focus without changes, the touched property is not modify...

For check that please add touched to the log on sample-date-picker-reactive-form.ts in the onSubmitReactiveForms() function...

```
onSubmitReactiveForms(): void {
        console.log('Value: ', this.myForm.controls['myDate'].value, ' - Valid: ', this.myForm.controls['myDate'].valid, ' - Dirty: ', this.myForm.controls['myDate'].dirty,  ' - Touched: ', this.myForm.controls['myDate'].touched);
    }
```

A workaround is to put blur event on each datepicker but if you can implement that it will be cool!

Workaround :
`public blurDp(event){       
       this.form.controls[event.target.id].markAsTouched();
       this.form.controls[event.target.id].updateValueAndValidity();
    }`

Thanks.

**Comment by kekeh** [comment]
This is fixed in version 2.0.13. In that version the blur event sets touched status of input field.
