### ISSUE TITLE
MarkDates and EnableDays from API

### ISSUE THREAD

**Issue by Alessio22** [kekeh/ngx-mydatepicker#62]
Hi,
I need to mark and enable days from an API when I change month or year.
This is my component:
`private dateModel: Object;
private dateOptions: IMyDpOptions = {
	minYear: 1970,
	maxYear: 2100,
	inline: true,
	dateFormat: 'dd/mm/yyyy',
	editableDateField: false,
}

ngOnInit() {
	let today = moment();
	this.dateModel = { date: { year: today.year(), month: today.month()+1, day: today.date() } };

	this.dateOptions['markDates'] = [{dates: [], color: '#ff0000'}];
	this.dateOptions['enableDays'] = [];
	this.dateOptions['disableDateRanges'] = [{ 
		begin: { year: 1970, month: 1, day: 1 },
		end: { year: 2100, month: 12, day: 31 } 
	}];
}	

onCalendarViewChanged (event: IMyCalendarViewChanged) {
	this.myService.getEnabledDay(event.month).subscribe( (days: number) => {
		this.dateOptions['enableDays'] = [];
		this.dateOptions['markDates'][0].dates = [];
		_.forEach(days, (day: number) => {
			this.dateOptions['markDates'][0].dates.push({ year: event.year, month: event.month, day: day });
			this.dateOptions['enableDays'].push({ year: event.year, month: event.month, day: day });
		});
	});	
}`
And this is my html:
`<my-date-picker name="dateModel" [options]="dateOptions" [(ngModel)]="dateModel" (calendarViewChanged)="onCalendarViewChanged($event)"></my-date-picker>`

How could I update my calendar instance dinamically to show new marks?

Thx

**Comment by kekeh** [comment]
You have to create copy of option and then set new values. Here is example: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

The example is disableUntil option but same principle works in all options.

**Comment by Alessio22** [comment]
It's works thx!
