### ISSUE TITLE
Manually entered dates without leading zeroes being ignored, treated as empty fields.

### ISSUE THREAD

**Issue by JaSpr** [kekeh/ngx-mydatepicker#63]
```html
<input class="form-control" placeholder="Select a date" ngx-mydatepicker
          [options]="{dateFormat: 'mm/dd/yyyy'}" [formControl]="formControl" #dp="ngx-mydatepicker"/>
    <button type="button" class="btn-calendar" (click)="dp.toggleCalendar();"></button>
```

We are using (basically) the above html for a datepicker.  This works great most of the time, especially when users use the calendar.  But, if a user was to enter a date such as `7/1/2017` the datepicker component will not recognize the date and return `null` instead of an `IMyDateModel` , because they did not use leading 0s.  This is the same value that `ngx-mydatepicker` returns for empty dates, so it leads our system to believe that the user didn't enter a date at all (which is a valid option), while leaving the user to think that their date was accepted.  

Users would have to enter `07/01/2017` or have the field act as if it is empty, which isn't clearly announced to the user.

**Comment by marcoschaule** [comment]
+1

**Comment by micdomingues** [comment]
Manually entered dates don't change the formControl (it continues untouched) too. ;/

**Comment by kekeh** [comment]
In 2.0.13 version the **blur** event sets touched status of the input field.

**Comment by JaSpr** [comment]
@kekeh any feedback on whether various dateformats (with single-digit dates or months) will be covered?  Our app uses the date formats associated with the user's locale, and our application is used globally.  Unfortunately, some locales have date formats which use `d` instead of `dd` or `m` instead of `mm`.

**Comment by JaSpr** [comment]
I should perhaps open a different bug regarding how telling NgxMyDatePicker that a format uses `d` or `m` makes it just not display the value at all.

`d/m/yyyy` would show as `d/m/2017`

**Comment by kekeh** [comment]
I added support to new date formats: For example: d.m.yyyy, dd.mm.yyyy, yyyy-m-d, yyyy-mm-dd, d mmm yyyy, dd mmm yyyy **(d = Day not leading zero, dd = Day with leading zero, m = Month not leading zero, mm = Month with leading zero, mmm = Month as a text, yyyy = Year four digit)**.

This change is in version 2.2.0
