### ISSUE TITLE
angular cli production build produces warnings for ngx-mydatepicker and error on click of calendar icon

### ISSUE THREAD

**Issue by devany1** [kekeh/ngx-mydatepicker#64]
Hi,
I am using ngx-mydatepicker version 2.0.12 in my angular 4 project. 
When I do a production build of my application using command "ng build --prod" I get the following warnings.

---------------------------------------
WARNING in ./~/ngx-myDatepicker/dist/services/ngx-my-date-picker.util.service.js                                                                                              
There are multiple modules with names that only differ in casing.                                                                                                             
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

WARNING in ./~/ngx-myDatepicker/dist/ngx-my-date-picker.component.js                                                                                                          
There are multiple modules with names that only differ in casing.                                                                                                             
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.      

WARNING in ./~/ngx-myDatepicker/dist/directives/ngx-my-date-picker.focus.directive.js                                                                                         
There are multiple modules with names that only differ in casing.                                                                                                             
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.   

---------------------------------------

After the build When I click on the calendar Icon I get the following error.

  ERROR Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
    at X (vendor.0484f1e….bundle.js:1)
    at t.resolveComponentFactory (vendor.0484f1e….bundle.js:1)
    at t.GLd3.t.openCalendar (vendor.0484f1e….bundle.js:1)
    at t.GLd3.t.toggleCalendar (vendor.0484f1e….bundle.js:1)
    at Object.handleEvent (main.3d6a0a4….bundle.js:1)
    at Object.A [as handleEvent] (vendor.0484f1e….bundle.js:1)
    at Object.handleEvent (vendor.0484f1e….bundle.js:1)
    at ie (vendor.0484f1e….bundle.js:1)
    at vendor.0484f1e….bundle.js:1
    at HTMLButtonElement.<anonymous> (vendor.0484f1e….bundle.js:1)
	
Any help would be appreciated.
Thanks

**Comment by kekeh** [comment]
Hi @devany1 

I don't know what is problem in your application but here is example application: https://github.com/kekeh/ngx-mydatepicker/tree/gh-pages

it uses Angular 4 and build works without warnings. Application is running here: https://kekeh.github.io/ngx-mydatepicker

**Comment by devany1** [comment]
Thanks @kekeh 

I was importing the date picker module as follows
import { NgxMyDatePickerModule } from 'ngx-myDatepicker';

because of capital D in the ngx-myDatepicker I was getting warnings in the production build. 

Closing the issue.
