### ISSUE TITLE
Updating options(disableUntil) of 'to' datepicker on selecting 'from' datepicker not working.

### ISSUE THREAD

**Issue by shifas** [kekeh/ngx-mydatepicker#68]
Have a 'from' datepicker and a 'to' datepicker. Setting disable until for 'to' datepicker on selecting 'from' datepicker doesn't seem to work.

**Comment by kekeh** [comment]
You have to create copy of options and then set value of the option. Here is an example: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

it is mydatepicker example but same principle works also with this component.
