### ISSUE TITLE
Incorrect datepicker positioning with bootstrap4

### ISSUE THREAD

**Issue by dsamoylov** [kekeh/ngx-mydatepicker#69]
I try to make this component work with my current project setup:
angular 4.3.3, bootstrap 4.0.0-alpha.6.

Since bootstrap 4 makes addon buttons look really ugly, I've changed HTML code from the exapmle and got rid if the buttons. Here my bootstrap 4 version:

```html
<div class="input-group">                         
  <input class="form-control" id="addDate" style="float:none"
               placeholder="Select a date" ngx-mydatepicker name="mydate"
               [(ngModel)]="model" [options]="myOptions" 
               #dp="ngx-mydatepicker" (dateChanged)="onDateChanged($event)"/>
  <span class="input-group-addon" (click)="dp.clearDate()" style="cursor:pointer;">
    <i class="fa fa-remove"></i>
  </span>
  <span class="input-group-addon" (click)="dp.toggleCalendar()" style="cursor:pointer;">
    <i class="fa fa-calendar"></i>
  </span>
</div>   
```

And here is how positioning works:

![2017-08-08_10h38_23](https://user-images.githubusercontent.com/5707036/29061276-cd31fdd2-7c25-11e7-8cfe-05d13e23b17b.png)

**Comment by kekeh** [comment]
It is because **display** type of **input-group** in bootstrap 4 is **flex**. In bootstrap 3 it was **table**. Duplicate: https://github.com/kekeh/ngx-mydatepicker/issues/56
