### ISSUE TITLE
dp.openCalendar() on input (focus) generates ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by budaii79** [kekeh/ngx-mydatepicker#72]
Hy, 

if I want to toggle the calendar when the input field is selected(clicked) it shows this error:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

The datepicker works ok  only that the error shows in console...

Can anybody give me a hint how to solve this?
It would be nice to toggle the calendar when the input field is clicked

**Comment by kekeh** [comment]
This error occurs normally only development version of the application. This worked ok in my test in development version of my application:
```html
<input ngx-mydatepicker name="mydate" [(ngModel)]="model" 
    [options]="myDatePickerOptions" #dp="ngx-mydatepicker" (click)="dp.openCalendar()"/>
```
If you are using old version of the component , update the latest version: 2.0.13

**Comment by dan-andreoli** [comment]
Hi,
the error is still present, you have to try it in reactive form with form control as required
