### ISSUE TITLE
I want date picker popup to stay even if user click on outside of it. How to do that?

### ISSUE THREAD

**Issue by parthajena** [kekeh/ngx-mydatepicker#76]
Currently i am implementing range picker using two date picker. I want the popup of each date picker to remain there even if user select the date or select any where in the page. But the popup is being hidden while i click out side the pop up.Please suggest.

In short, i want datepicker popup to always remain open. The only way we can close is by calling dp.closeCalendar(). Please suggest.Thanks in advance. If more input needed please let me know.

**Comment by kekeh** [comment]
Hi @parthajena 

I added new option **closeSelectorOnDocumentClick** which default value is **true**. Set it to **false** in options and selector is not closed on document click.

This change is in version 2.0.15. Please update to this version at first.

**Comment by parthajena** [comment]
Thanks a lot :)
