### ISSUE TITLE
How to select a particular date in date picker popup from outside(click of a button). 

### ISSUE THREAD

**Issue by parthajena** [kekeh/ngx-mydatepicker#78]
Hi,
I want the selected date in the date-picker popup to be changed depending on the click of a button from outside. For now i am changing the ngmodel of the date picker.  The model value is updated but in popup it is not selecting the new one.

Is there way we can select/deselect date in the popup from outside event.Please suggest.

**Comment by kekeh** [comment]
It is possible set date two ways (**jsdate** or **date** properties). See below. Setting model value to **null** clears the selected date.

```html
<input ngx-mydatepicker name="mydate" [(ngModel)]="model" 
    [options]="myDatePickerOptions"  #dp="ngx-mydatepicker" />

<button type="button" (click)="setWithJsDate()">Set date with jsdate</button>
<button type="button" (click)="setWithIMyDate()">Set date with IMyDate</button>
<button type="button" (click)="clearDate()">Clear date</button>
```

```javascript
private model: any = null;   // not initial date set

setWithJsDate(): void {
    // set today
    this.model = {jsdate: new Date()};
}

setWithIMyDate(): void {
    // set today
    this.model = {date: {year: 2017, month: 9, day: 4}};
}

clearDate(): void {
    // clear the selected date
    this.model = null;
}
```

**Comment by parthajena** [comment]
Hi Kekeh,

Thanks for your response.
Basically i want the selection in the popup to be changed while the date-picker popup is still open.Seems like model is updated but the selection in the UI is not updated.If i close the popup and again open then it is set to correct value.

Is there any way we can change the value and able to see the change in selection while the date-picker popup is still open.
If more clarification needed in my question please let me know.

Thanks again,
Partha

**Comment by kekeh** [comment]
Unfortunately this is not possible with current version. You have to open popup of datepicker to see selection on calendar.
