### ISSUE TITLE
DatePicker window isn't aligning with textbox

### ISSUE THREAD

**Issue by emersoncpaz** [kekeh/ngx-mydatepicker#81]
How to configure datepicker position? I'm using MdInput from angular/material but the datepicker isn't aliging with textbox. The box is shown in front of textbox, not above.

**Comment by kekeh** [comment]
I have fixed invalid calendar position issue here: https://github.com/kekeh/ngx-mydatepicker/issues/56

If you are using an old version update to **2.1.0** version which contain above fix. I haven't tested this date picker with **MdInput** component so it is difficult to say.

I have tested only simple input box like below:

```html
<input ngx-mydatepicker name="mydate"
    [(ngModel)]="model" [options]="myDatePickerOptions" #dp="ngx-mydatepicker"
    (dateChanged)="onDateChanged($event)" />
```

Is calendar position right with example above?
