### ISSUE TITLE
On selecting date in one date picker will automatically select date in other date field.

### ISSUE THREAD

**Issue by lakhvir1994** [kekeh/ngx-mydatepicker#82]
I am working on angular 4 application and I am using this date picker.
When I am selecting date in one date field it will automatically select the date in another date field.
Typescript:
`
public calendarOptions: INgxMyDpOptions = {
      // other options...
      dateFormat: 'mm/dd/yyyy',
      disableUntil: this.getYesterdayDate()
   };
specificDates            : any = [];

addSpecificDate()
   {
      (this.specificDates).push("");      
   }

onSpecificDateSelect(event, index)
   {
      this.specificDates[index] = event.formatted;
   }
`

Template:
`
<ng-container *ngFor="let date of specificDates; let i = index ">
     <div>
         <input 
                  placeholder="MM/DD/YYYY"  ngx-mydatepicker 
                  [options]="calendarOptions" 
                  #specific_date ="ngx-mydatepicker" 
                  (click)="specific_date.toggleCalendar()" 
                  [value]="date" (dateChanged)="onSpecificDateSelect($event, i)" 
                  readonly
           >
           <i class="material-icons" (click)="specific_date.toggleCalendar()">event</i>
     </div>
     <div>
          <i class="material-icons" *ngIf="i == 0" (click)="addSpecificDate()">add_box</i>
          <i class="material-icons" *ngIf="i != 0" (click)="removeSpecificDate(date, i)">indeterminate_check_box</i>
      </div>
</ng-container>
`

When I select specific date 1 then it will automatically select date in specific date 2, If I select specific date 2 then it will automatically select specific date 3.
I don't know why it is happening.

**Comment by kekeh** [comment]
Try to copy event as follows:
```javascript
onSpecificDateSelect(event: any, index: number): void {
    let copy: any = this.getCopy(event);
    this.specificDates[index] = copy.formatted;
}

getCopy(event: any): any {
    return JSON.parse(JSON.stringify(event));
}
```

**Comment by lakhvir1994** [comment]
I have tried this but getting the same issue.

**Comment by kekeh** [comment]
You can use separate variable to store the selected dates as follows:
```html
<div *ngFor="let d of datePickers; let i = index">
    <div class="input-group">
        <input class="form-control" style="float:none" ngx-mydatepicker
                                   [options]="myDatePickerOptions" #dp="ngx-mydatepicker"
                                   (dateChanged)="onDateChanged($event, i)"/>

        <span class="input-group-btn">
            <button type="button" class="btn btn-default" (click)="dp.clearDate()"><i class="glyphicon glyphicon-remove"></i></button>
            <button type="button" class="btn btn-default" (click)="dp.toggleCalendar()"><i class="glyphicon glyphicon-calendar"></i></button>
        </span>
    </div>
 </div>
```

```javascript
datePickers : Array<string> = ['', '', '']; // create 3 date pickers
selectedDates : Array<string> = [];

onDateChanged(event: IMyDateModel, index: number): void {
    this.selectedDates[index] = event.formatted;
}
```

**Comment by lakhvir1994** [comment]
Thank you so much for your support.

**Comment by lakhvir1994** [comment]
public removeSpecificDate(index: number)
   {
      this.specificDates.splice(index, 1);
      this.specificDatesTimestamp.splice(index, 1);
   }

When I am trying to remove specific date by clicking - icon associated with each specific date, It not work properly.
I will explain you by giving and example : If I have added 3 specific date fields and select date in 2nd field and when I remove 2nd field it removes from both arrays but it displays date in 2nd field. Functionality wise it is working properly but visually it is not working.
