### ISSUE TITLE
Always show calendar without clicking on input field?

### ISSUE THREAD

**Issue by 02harleen** [kekeh/ngx-mydatepicker#83]
I am using your date picker and I have requirement of a calendar which will never close or I say that the calendar should be visible always.

**Comment by kekeh** [comment]
It is not possible with **ngx-mydatepicker** but you can use **mydatepicker** (https://github.com/kekeh/mydatepicker) which supports **inline** mode.

Here is demo of **mydatepicker** with **inline** mode: http://kekeh.github.io/mydatepicker/#inlinemode
