### ISSUE TITLE
why my calendar behind my modal window

### ISSUE THREAD

**Issue by vicabelotelova** [kekeh/ngx-mydatepicker#84]
i use ng2-bs3-modal and ngx-mydatepicker. Why this happening when i click on calendar

Everything was fine, until npm updated the version of the datapicker to 2.1.0
![image](https://user-images.githubusercontent.com/20780164/30468729-88502eee-99f5-11e7-9f38-5817ad63006b.png)
```
<modal [cssClass]="'modal-lg'" tabindex="-1" role="dialog" [backdrop]="'static'" #AddDocumentsModal >
      <modal-header>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title text-center">Add Documents</h1>
      </modal-header>
<modal-body>
<div class="form-group" >
	  <label class="col-md-4 control-label" for="DocumentDate" >Date*</label>  
	   <div class="input-group form-group col-md-5" style="width: 375px;float: left;margin-left: 15px;z-index: 1">
	    <input class="form-control" style="float:none" placeholder="Выберите дату" ngx-mydatepicker
	     [(ngModel)]="DocumentDateModel" [ngModelOptions]="{standalone: true}" [options]="myOptions" #date="ngx-mydatepicker" (dateChanged)="onDateChanged($event)" required maxlength="10" mask="00.00.0000" />
	    <span class="input-group-btn">
	        <button type="button" class="btn btn-default" (click)="date.clearDate()">
	            <i class="glyphicon glyphicon-remove"></i>
	        </button>
	        <button type="button" class="btn btn-default" (click)="date.toggleCalendar()">
	            <i class="glyphicon glyphicon-calendar"></i>
	        </button>
	    </span>
	</div>
	</div>
<modal-footer>
	<button class="btn btn-primary" (click)="close(addDocuments)">Close</button>
</modal-footer>
</modal>
```

**Comment by paulstringerdb** [comment]
Exactly the same issue...

**Comment by vicabelotelova** [comment]
@paulstringerdb thanks a lot

**Comment by kodaren** [comment]
As far as I can see it's because the element is anchored to the body (issue 56). It works fine in 2.0.16. This should maybe be an optional parent selector?

**Comment by kekeh** [comment]
I increased the value of **z-index** to **100000**. This change is in version **2.1.1**.

**Comment by yogeshfcc** [comment]
@kekeh This issue is not resolved yet, Date Picker is still not rendering correctly on modal window. I am using **ng2-bs3-modal** and **ngx-mydatepicker**. This is happening on latest version _**2.1.2**_

![ngx-mydatepicker](https://user-images.githubusercontent.com/29005248/30688108-ec8bfb10-9eda-11e7-87e2-dbcf8125fe61.jpg)

**Comment by kekeh** [comment]
@yogeshfcc 

In your case you have some global style definition somewhere. You have to select date picker header with right mouse and select inspect from the menu. Then disable one by one styles to see which causes issue. Probably style definition is html table related.
