### ISSUE TITLE
Using Tab key on a form which contains the date picker triggers (dateChanged) event

### ISSUE THREAD

**Issue by karthikv-26** [kekeh/ngx-mydatepicker#87]
First of all thanks for this great date picker!.

Suppose I have three form element. Two of them are plain input text box and third one is date picker. I use Tab key to navigate between the three elements. But when Date picker is attained focus from a tab key press event it triggers (dateChanged) event which is not right. But same does not happen when focused through Mouse click event.

Focusing through tab should simply focus the element and be used for navigation on a form and it should not trigger any event.

**Comment by kekeh** [comment]
Here is not **dateChanged** event triggered when tab is pressed multiple times: https://kekeh.github.io/ngx-mydatepicker/

You can see it from console of the browser.

**Comment by karthikv-26** [comment]
Did you select a date from the date picker? Please have a date selected and then try to focus on date picker using "Tab" Event. If there is no date then "dateChanged" is not called, But when there is a date already selected then it gets called.

I verified the same by testing it on https://kekeh.github.io/ngx-mydatepicker/
and issue still exists when there is a date value present in the date picker

**Comment by kekeh** [comment]
True. I fixed this issue. Update the latest version **2.1.2**.
