### ISSUE TITLE
Calendar will be scrolled

### ISSUE THREAD

**Issue by vicabelotelova** [kekeh/ngx-mydatepicker#88]
When I call the calendar event and start scrolling the page, the calendar scrolls along with the page

![image](https://user-images.githubusercontent.com/20780164/30687632-9899fad6-9ec4-11e7-9578-2c5515398b90.png)
![image](https://user-images.githubusercontent.com/20780164/30687641-a359dad6-9ec4-11e7-92df-a65de4c30407.png)

i set style 
`.ngxmdp .selector {
    z-index: 100000 !important;
}
`

because my calendar was under my modal window

**Comment by kekeh** [comment]
Scrolling issue is a bug. I will try to fix it on next weekend.

You don't need to set:
```css
.ngxmdp .selector { z-index: 100000 !important; }
```

just install the latest version 2.1.3 and it set z-index value behalf of you.

**Comment by kekeh** [comment]
Scrolling with open calendar works fine here: https://kekeh.github.io/ngx-mydatepicker/

make height of the browser window smaller to see scroll bar if necessary

Maybe this bug is related somehow to modal window? 

Quick workaround is close the calendar if scroll event occurs:
```ts
@ViewChild('dp') ngxdp: any;  // you have local variable dp in HTML. For example #dp="ngx-mydatepicker"

@HostListener("window:scroll", ["$event"]) onScroll(event: any) {
    if(this.calendarOpen) {
        // close calendar
        this.ngxdp.closeCalendar();
        this.calendarOpen = false;
    }
    
}
```

**Comment by vicabelotelova** [comment]
@kekeh what is the variable "this.calendarOpen". And how i can use it

**Comment by kekeh** [comment]
You can define that variable and keep It up to date. Purpose of It is to prevent unnecessary closeCalendar() calls.

**Comment by vicabelotelova** [comment]
its not working in my angular version 2.4.1
or i am doing something wrong

**Comment by kekeh** [comment]
You have to define **#dp="ngx-mydatepicker"** in the input box.

Then code below should work.
```ts
@ViewChild('dp') ngxdp: any; 

@HostListener("window:scroll", ["$event"]) onScroll(event: any) {
    // close calendar
    this.ngxdp.closeCalendar();
    console.log('onScroll()');
}
```

If you add console.log to the onScroll method. Can you see **onScroll()** message in the console of the browser when you scroll the modal?

It should also work with the version of Angular you have.

**Comment by vicabelotelova** [comment]
With bs3-ng2-modal it's work like this
```typescript
@ViewChild('dp') ngxdp: any; 

@HostListener("scroll", ["$event"]) onScroll(event: 
    console.log('onScroll()');
}
```
```html
<modal [cssClass]="'modal-lg'" tabindex="-1" role="dialog" [backdrop]="'static'" #viewEDS (scroll)=onScroll($event)">
<modal-header>
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</modal-header>
<modal-body >
	
</modal-body>

<modal-footer >
	
</modal-footer>
</modal>
```

**Comment by kekeh** [comment]
Can you try version 2.1.5. Probably it is not now moving when scroll the modal.
