### ISSUE TITLE
/dist not distributed in 0.0.9

### ISSUE THREAD

**Issue by daveriedstra** [kekeh/ngx-mydatepicker#9]
After updating to 0.0.9 with `npm i -S ngx-mydatepicker@0.0.9`, my project build exploded because `/dist` wasn't present in the ngx-mydatepicker node_modules folder.

**Comment by kekeh** [comment]
I tried your command and it worked ok. The dist folder was present under the 
node_modules/ngx-mydatepicker folder. 

There is also newer version 0.1.0 available. Try that again.

**Comment by daveriedstra** [comment]
you're right, upgrading to 0.0.9 worked fine the second time. wonder what it could have been. 0.1.0 works great too. sorry for the headache.
