### ISSUE TITLE
Please change minYear to 1000 and maxYear to 9999

### ISSUE THREAD

**Issue by Martin-Wegner** [kekeh/ngx-mydatepicker#91]
The current `minYear` is **1100** and the current `maxYear` is **9100**. My application needs `maxYear` **9999** and your https://github.com/kekeh/mydatepicker also uses `minYear` **1000** and `maxYear` **9999**. I will make a PR.

Thanks in advance!

**Comment by kekeh** [comment]
I merged your PR. New version of the component is **2.1.3**.

**Comment by Martin-Wegner** [comment]
Thanks :)
