### ISSUE TITLE
one or more input date picker 

### ISSUE THREAD

**Issue by jadhavpravinei** [kekeh/ngx-mydatepicker#94]
How can i use more date picker in one form ??

**Comment by kekeh** [comment]
Just add multiple input box which each contain ngx-mydatepicker directive and other related stuff. You have to define own ngModel variable to each date picker.

Here is an example on how to add one date picker using ngModel binding: https://github.com/kekeh/ngx-mydatepicker#1-ngmodel-binding

**Comment by jadhavpravinei** [comment]
yes i did it before thanks for the replay its working
