### ISSUE TITLE
Datepicker remains open when I change route before closing toggle

### ISSUE THREAD

**Issue by aks1994** [kekeh/ngx-mydatepicker#96]
My datepicker is in a component A that appears in a given route e.g.: "/abc". If the datepicker is open and I click on a routerlink that takes me to another component D through say route "/def", the datepicker still remains open and overflows over component D.

I checked and component A does get destroyed through the route change, but still the toggle remains open. Any ideas why this is happening and how I can correct this behavior? Is this a bug?

**Comment by kekeh** [comment]
Calendar is appended to **body** element and that is why it remains open when you change a route. You have to call **closeCalendar()** function before changing the route in order to be sure calendar closes.

**Comment by kekeh** [comment]
For example:
```html
<input ngx-mydatepicker [(ngModel)]="model" [options]="myOptions" #dp="ngx-mydatepicker"/>
```

```javascript
export class MyComponent implements OnDestroy {

    @ViewChild('dp') ngxdp: NgxMyDatePickerDirective;

    ngOnDestroy() {
        this.ngxdp.closeCalendar();
    }
}
```

**Comment by aks1994** [comment]
Thanks for the clarification!
