### ISSUE TITLE
Dynamically changing options, undocumented

### ISSUE THREAD

**Issue by ayyash** [kekeh/ngx-mydatepicker#99]
Today I tried a method that is not documented to change options dynamically, I'm asking to verify this way works:

An input with `#dtpciker="ngx-mydatepicker"`  set, and `(dateChanged)="doSomething($event, dtpicker)"`
So basically Im sending back an instance of the picker with its options, then in typescript:
```
	doSomething(event: IMyDateModel, picker: NgxMyDatePickerDirective) {
		// set minimum of picker
		picker.options.disableSince = { year: event.date.year, month: event.date.month, day: event.date.day };
		// does this work?
		picker.parseOptions(picker.options);
	}
```
Apparently it works, but since it isn't documented, what are the side effects of doing this? Notice that assigning the options directly did not do it, I had to use the parseOptions

**Comment by kekeh** [comment]
You need to create copy of options at first and then update the value. This example is from mydatepicker but it works also here: https://github.com/kekeh/mydatepicker/wiki/Two-date-pickers-set-options

other example from mydatepicker: https://github.com/kekeh/mydatepicker/wiki/Set-disableUntil-option

All options can be changed dynamically.

**Comment by ayyash** [comment]
I tried the example you stated, this line
`this.endDate = copy;`
doesn't work, it did not update my picker. I have two pickers (exactly the same range example), and I tried this without cloning first, and it works, simply because I do not change the options object, im changing the picker's own instance options, which is already a singleton, not so?

**Comment by kekeh** [comment]
It should work. Here is working example. It sets dynamically almost all options one by one: https://github.com/kekeh/ngx-mydatepicker/blob/master/examples/sample-date-picker-ngmodel/sample-date-picker-ngmodel.ts

**Comment by ayyash** [comment]
Yes you're right, it works if the options are a shared object (naturally cloning is a must), but if you want to have multiple date controls with options object for each, direct assignment did not update, the parseOptions did it, its a great feature I think you should include it in your wiki
